// ui/src/components/Report/MarineConnectivity.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Text, View } from '@react-pdf/renderer'

import { formatNumber, pluralize } from 'util/format'
import { Bold, Flex, Section } from './elements'

const MarineConnectivity = ({
  barrierType,
  milestooutlet,
  totaldownstreamdams,
  totaldownstreamsmallbarriers,
  totaldownstreamwaterfalls,
  ...props
}) => (
  <Section title="Marine connectivity" {...props} wrap={false}>
    <Flex>
      <View
        style={{
          flex: '1 1 25%',
        }}
      >
        <Text>
          <Bold>{formatNumber(milestooutlet)}</Bold>{' '}
          {pluralize('mile', milestooutlet)} downstream to the ocean
        </Text>
      </View>

      {totaldownstreamdams >= 0 ? (
        <View
          style={{
            flex: '1 1 25%',
            marginLeft: 14,
            paddingLeft: 14,
            borderLeft: '1px solid #cfd3d6',
          }}
        >
          <Text>
            <Bold>{formatNumber(totaldownstreamdams)}</Bold>{' '}
            {pluralize('dam', totaldownstreamdams)} downstream
          </Text>
        </View>
      ) : null}

      {barrierType === 'small_barriers' && totaldownstreamsmallbarriers >= 0 ? (
        <View
          style={{
            flex: '1 1 25%',
            marginLeft: 14,
            paddingLeft: 14,
            borderLeft: '1px solid #cfd3d6',
          }}
        >
          <Text>
            <Bold>{formatNumber(totaldownstreamsmallbarriers)}</Bold> assessed
            road-related {pluralize('barrier', totaldownstreamsmallbarriers)}{' '}
            downstream
          </Text>
        </View>
      ) : null}

      {totaldownstreamwaterfalls >= 0 ? (
        <View
          style={{
            flex: '1 1 25%',
            marginLeft: 14,
            paddingLeft: 14,
            borderLeft: '1px solid #cfd3d6',
          }}
        >
          <Text>
            <Bold>{formatNumber(totaldownstreamwaterfalls)}</Bold>{' '}
            {pluralize('waterfall', totaldownstreamwaterfalls)} downstream
          </Text>
        </View>
      ) : null}
    </Flex>
  </Section>
)

MarineConnectivity.propTypes = {
  barrierType: PropTypes.string.isRequired,
  milestooutlet: PropTypes.number,
  totaldownstreamdams: PropTypes.number,
  totaldownstreamsmallbarriers: PropTypes.number,
  totaldownstreamwaterfalls: PropTypes.number,
}

MarineConnectivity.defaultProps = {
  milestooutlet: 0,
  totaldownstreamdams: 0,
  totaldownstreamsmallbarriers: 0,
  totaldownstreamwaterfalls: 0,
}

export default MarineConnectivity

// ui/src/lib/components/report/MarineConnectivity.svelte
<script lang="ts">
	import { formatNumber, pluralize } from '$lib/util/format'

	const {
		barrierType,
		milestooutlet,
		totaldownstreamdams,
		totaldownstreamsmallbarriers,
		totaldownstreamwaterfalls
	} = $props()

	const numCols = $derived(
		1 +
			Number(totaldownstreamdams >= 0) +
			Number(barrierType === 'small_barriers' && totaldownstreamsmallbarriers >= 0) +
			Number(totaldownstreamwaterfalls >= 0)
	)
</script>

<section>
	<h2>Marine connectivity</h2>

	<div
		class={`grid sm:grid-cols-${numCols} gap-4 mt-4 leading-snug sm:[&>div]:py-2 sm:[&>div+div]:border-l sm:[&>div+div]:border-l-grey-2 sm:[&>div+div]:pl-4`}
	>
		<div>
			<b>{formatNumber(milestooutlet)}</b>
			{pluralize('mile', milestooutlet)} downstream to the ocean
		</div>

		{#if totaldownstreamdams >= 0}
			<div>
				<b>{formatNumber(totaldownstreamdams)}</b>
				{pluralize('dam', totaldownstreamdams)} downstream
			</div>
		{/if}

		{#if barrierType === 'small_barriers' && totaldownstreamsmallbarriers >= 0}
			<div>
				<b>{formatNumber(totaldownstreamsmallbarriers)}</b> assessed road-related {pluralize(
					'barrier',
					totaldownstreamsmallbarriers
				)}
				downstream
			</div>
		{/if}

		{#if totaldownstreamwaterfalls >= 0}
			<div>
				<b>{formatNumber(totaldownstreamwaterfalls)}</b>
				{pluralize('waterfall', totaldownstreamwaterfalls)} downstream
			</div>
		{/if}
	</div>
</section>
