// ui/src/components/ReportPreview/SpeciesWatershedPresence.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Box, Heading, Grid, Paragraph, Text } from 'theme-ui'

import { SALMONID_ESU, TROUT } from 'config'
import { formatNumber } from 'util/format'

const SpeciesWatershedPresence = ({
  barrierType,
  tespp,
  statesgcnspp,
  regionalsgcnspp,
  trout,
  salmonidesu,
  sx,
}) => {
  const troutSpp = trout ? trout.split(',').map((code) => TROUT[code]) : []

  return (
    <Box sx={sx}>
      <Heading as="h3">Species information for this subwatershed</Heading>

      <Box>
        Data sources in the subwatershed containing this{' '}
        {barrierType === 'dams' ? 'dam' : 'road-related barrier'} have recorded:
      </Box>

      <Grid
        columns={3}
        gap={0}
        sx={{
          mt: '1rem',
          '&>div': {
            py: '0.5em',
          },
          '&> div + div': {
            ml: '1rem',
            pl: '1rem',
            borderLeft: '1px solid',
            borderLeftColor: 'grey.3',
          },
        }}
      >
        <Box>
          <b>{formatNumber(tespp)}</b> federally-listed threatened and
          endangered aquatic species
        </Box>
        <Box>
          <b>{statesgcnspp}</b> state-listed aquatic Species of Greatest
          Conservation Need (SGCN)
        </Box>
        <Box>
          <b>{regionalsgcnspp}</b> regionally-listed aquatic Species of Greatest
          Conservation Need
        </Box>
      </Grid>

      <Box sx={{ mt: '1.5rem' }}>
        <Text>
          {trout
            ? `This subwatershed includes recorded observations of ${troutSpp.join(troutSpp.length === 2 ? ' and ' : ', ')}.`
            : 'No interior or eastern native trout species have been recorded in this subwatershed.'}
        </Text>
      </Box>

      {salmonidesu ? (
        <Text sx={{ mt: '1.5rem' }}>
          This subwatershed falls within the following salmon Evolutionarily
          Significant Units (ESU) / steelhead trout Discrete Population Segments
          (DPS):
          <Box as="ul" sx={{ mt: '0.25rem', ml: '1rem' }}>
            {salmonidesu.split(',').map((code) => (
              <li key={code}>{SALMONID_ESU[code]}</li>
            ))}
          </Box>
        </Text>
      ) : null}

      <Paragraph variant="help" sx={{ mt: '2rem', fontSize: 0 }}>
        Note: State and regionally listed species of greatest conservation need
        may include state-listed threatened and endangered species. Trout
        species presence is based on occurrences of Apache, brook, bull,
        cutthroat, Gila, lake, and redband trout species. Species information is
        very incomplete and only includes species that have been identified by
        available data sources for this subwatershed. These species may or may
        not be directly impacted by this barrier. The absence of species in the
        available data does not necessarily indicate the absence of species in
        the subwatershed.
      </Paragraph>
    </Box>
  )
}

SpeciesWatershedPresence.propTypes = {
  barrierType: PropTypes.string.isRequired,
  tespp: PropTypes.number,
  statesgcnspp: PropTypes.number,
  regionalsgcnspp: PropTypes.number,
  trout: PropTypes.string,
  salmonidesu: PropTypes.string,
  sx: PropTypes.object,
}

SpeciesWatershedPresence.defaultProps = {
  tespp: 0,
  statesgcnspp: 0,
  regionalsgcnspp: 0,
  trout: null,
  salmonidesu: null,
  sx: null,
}

export default SpeciesWatershedPresence

// ui/src/lib/components/report/SpeciesWatershedPresence.svelte
<script lang="ts">
	import { SALMONID_ESU, TROUT } from '$lib/config/constants'
	import { formatNumber } from '$lib/util/format'

	const { barrierType, tespp, statesgcnspp, regionalsgcnspp, trout, salmonidesu } = $props()
	const troutSpp = $derived(
		trout ? trout.split(',').map((code: keyof typeof TROUT) => TROUT[code]) : []
	)
</script>

<section>
	<h2>Species information for this subwatershed</h2>

	<div class="text-sm">
		Data sources in the subwatershed containing this
		{barrierType === 'dams' ? 'dam' : 'road-related barrier'} have recorded:
	</div>

	<div
		class="grid sm:grid-cols-3 gap-4 text-sm mt-4 leading-snug sm:[&>div]:py-2 sm:[&>div+div]:border-l sm:[&>div+div]:border-l-grey-2 sm:[&>div+div]:pl-4"
	>
		<div>
			<b>{formatNumber(tespp)}</b> federally-listed threatened and endangered aquatic species
		</div>
		<div>
			<b>{statesgcnspp}</b> state-listed aquatic Species of Greatest Conservation Need (SGCN)
		</div>
		<div>
			<b>{regionalsgcnspp}</b> regionally-listed aquatic Species of Greatest Conservation Need
		</div>
	</div>

	<div class="mt-6 text-sm">
		{#if trout}This subwatershed includes recorded observations of {troutSpp.join(
				troutSpp.length === 2 ? ' and ' : ', '
			)}.
		{:else}
			No interior or eastern native trout species have been recorded in this subwatershed.
		{/if}
	</div>

	{#if salmonidesu}
		<div class="mt-6 text-sm">
			This subwatershed falls within the following salmon Evolutionarily Significant Units (ESU) /
			steelhead trout Discrete Population Segments (DPS):
			<ul class="list-disc list-outside mt-1 pl-8">
				{#each salmonidesu.split(',') as code (code)}
					<li>{SALMONID_ESU[code as keyof typeof SALMONID_ESU]}</li>
				{/each}
			</ul>
		</div>
	{/if}

	<div class="text-xs text-muted-foreground mt-8">
		Note: State and regionally listed species of greatest conservation need may include state-listed
		threatened and endangered species. Trout species presence is based on occurrences of Apache,
		brook, bull, cutthroat, Gila, lake, and redband trout species. Species information is very
		incomplete and only includes species that have been identified by available data sources for
		this subwatershed. These species may or may not be directly impacted by this barrier. The
		absence of species in the available data does not necessarily indicate the absence of species in
		the subwatershed.
	</div>
</section>
