// ui/src/components/Report/SpeciesWatershedPresence.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Text, View } from '@react-pdf/renderer'

import { SALMONID_ESU, TROUT } from 'config'
import { formatNumber } from 'util/format'

import { Bold, Flex, List, ListItem, Section } from './elements'

const SpeciesWatershedPresence = ({
  barrierType,
  tespp,
  statesgcnspp,
  regionalsgcnspp,
  trout,
  salmonidesu,
  ...props
}) => {
  const troutSpp = trout ? trout.split(',').map((code) => TROUT[code]) : []

  return (
    <Section
      title="Species information for this subwatershed"
      {...props}
      wrap={false}
    >
      <View>
        <Text>
          Data sources in the subwatershed containing this{' '}
          {barrierType === 'dams' ? 'dam' : 'road-related barrier'} have
          recorded:
        </Text>
      </View>

      <Flex style={{ marginTop: 24 }}>
        <View
          style={{
            flex: '1 1 25%',
          }}
        >
          <Text>
            <Bold>{formatNumber(tespp)}</Bold> federally-listed threatened and
            endangered aquatic species
          </Text>
        </View>

        <View
          style={{
            flex: '1 1 25%',
            marginLeft: 14,
            paddingLeft: 14,
            borderLeft: '1px solid #cfd3d6',
          }}
        >
          <Text>
            <Bold>{statesgcnspp}</Bold> state-listed aquatic Species of Greatest
            Conservation Need (SGCN)
          </Text>
        </View>

        <View
          style={{
            flex: '1 1 25%',
            marginLeft: 14,
            paddingLeft: 14,
            borderLeft: '1px solid #cfd3d6',
          }}
        >
          <Text>
            <Bold>{regionalsgcnspp}</Bold> regionally-listed aquatic Species of
            Greatest Conservation Need
          </Text>
        </View>
      </Flex>

      <View style={{ marginTop: 14 }}>
        <Text>
          {trout
            ? `This subwatershed includes recorded observations of ${troutSpp.join(troutSpp.length === 2 ? ' and ' : ', ')}.`
            : 'No interior or eastern native trout species have been recorded in this subwatershed.'}
        </Text>
      </View>

      {salmonidesu ? (
        <View style={{ marginTop: 14 }}>
          <Text>
            This subwatershed falls within the following salmon Evolutionarily
            Significant Units (ESU) / steelhead trout Discrete Population
            Segments (DPS):
          </Text>
          <List style={{ marginLeft: 12 }}>
            {salmonidesu.split(',').map((code) => (
              <ListItem key={code}>
                <Text>{SALMONID_ESU[code]}</Text>
              </ListItem>
            ))}
          </List>
        </View>
      ) : null}

      <Text style={{ color: '#7f8a93', marginTop: 24, fontSize: 10 }}>
        Note: State and regionally listed species of greatest conservation need
        may include state-listed threatened and endangered species. Trout
        species presence is based on occurrences of Apache, brook, bull,
        cutthroat, Gila, lake, and redband trout species. Species information is
        very incomplete and only includes species that have been identified by
        available data sources for this subwatershed. These species may or may
        not be directly impacted by this barrier. The absence of species in the
        available data does not necessarily indicate the absence of species in
        the subwatershed.
      </Text>
    </Section>
  )
}

SpeciesWatershedPresence.propTypes = {
  barrierType: PropTypes.string.isRequired,
  tespp: PropTypes.number,
  statesgcnspp: PropTypes.number,
  regionalsgcnspp: PropTypes.number,
  trout: PropTypes.string,
  salmonidesu: PropTypes.string,
}

SpeciesWatershedPresence.defaultProps = {
  tespp: 0,
  statesgcnspp: 0,
  regionalsgcnspp: 0,
  trout: null,
  salmonidesu: null,
}

export default SpeciesWatershedPresence

// ui/src/lib/components/report/SpeciesWatershedPresence.svelte
<script lang="ts">
	import { SALMONID_ESU, TROUT } from '$lib/config/constants'
	import { formatNumber } from '$lib/util/format'

	const { barrierType, tespp, statesgcnspp, regionalsgcnspp, trout, salmonidesu } = $props()
	const troutSpp = $derived(
		trout ? trout.split(',').map((code: keyof typeof TROUT) => TROUT[code]) : []
	)
</script>

<section>
	<h2>Species information for this subwatershed</h2>

	<div class="text-sm">
		Data sources in the subwatershed containing this
		{barrierType === 'dams' ? 'dam' : 'road-related barrier'} have recorded:
	</div>

	<div
		class="grid sm:grid-cols-3 gap-4 text-sm mt-4 leading-snug sm:[&>div]:py-2 sm:[&>div+div]:border-l sm:[&>div+div]:border-l-grey-2 sm:[&>div+div]:pl-4"
	>
		<div>
			<b>{formatNumber(tespp)}</b> federally-listed threatened and endangered aquatic species
		</div>
		<div>
			<b>{statesgcnspp}</b> state-listed aquatic Species of Greatest Conservation Need (SGCN)
		</div>
		<div>
			<b>{regionalsgcnspp}</b> regionally-listed aquatic Species of Greatest Conservation Need
		</div>
	</div>

	<div class="mt-6 text-sm">
		{#if trout}This subwatershed includes recorded observations of {troutSpp.join(
				troutSpp.length === 2 ? ' and ' : ', '
			)}.
		{:else}
			No interior or eastern native trout species have been recorded in this subwatershed.
		{/if}
	</div>

	{#if salmonidesu}
		<div class="mt-6 text-sm">
			This subwatershed falls within the following salmon Evolutionarily Significant Units (ESU) /
			steelhead trout Discrete Population Segments (DPS):
			<ul class="list-disc list-outside mt-1 pl-8">
				{#each salmonidesu.split(',') as code (code)}
					<li>{SALMONID_ESU[code as keyof typeof SALMONID_ESU]}</li>
				{/each}
			</ul>
		</div>
	{/if}

	<div class="text-xs text-muted-foreground mt-8">
		Note: State and regionally listed species of greatest conservation need may include state-listed
		threatened and endangered species. Trout species presence is based on occurrences of Apache,
		brook, bull, cutthroat, Gila, lake, and redband trout species. Species information is very
		incomplete and only includes species that have been identified by available data sources for
		this subwatershed. These species may or may not be directly impacted by this barrier. The
		absence of species in the available data does not necessarily indicate the absence of species in
		the subwatershed.
	</div>
</section>
