// ui/src/components/BarrierDetails/Header.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Box, Button, Flex, Heading, Text } from 'theme-ui'
import {
  DraftingCompass,
  FileDownload,
  Fish,
  Water,
} from '@emotion-icons/fa-solid'

import { STATES } from 'config'
import { formatNumber } from 'util/format'
import { isEmptyString } from 'util/string'

const Header = ({
  barrierType,
  networkType,
  sarpid,
  name,
  county,
  state,
  lat,
  lon,
  removed,
  yearremoved,
  isPriority,
  isSurveyed,
  onClose,
}) => (
  <Box
    sx={{
      py: '0.5rem',
      px: '0.5rem',
      borderBottom: '4px solid',
      borderBottomColor: 'blue.2',
    }}
  >
    <Flex
      sx={{
        flex: '0 0 auto',
        justifyContent: 'space-between',
      }}
    >
      <Box sx={{ flex: '1 1 auto', mb: '0.5rem' }}>
        <Heading as="h3" sx={{ m: 0, fontSize: '1.25rem' }}>
          {name}
        </Heading>
        {removed ? (
          <Flex
            sx={{
              alignItems: 'center',
              gap: '0.5rem',
              mt: '0.25rem',
            }}
          >
            <Box sx={{ color: 'blue.8' }}>
              <Water size="1em" />
            </Box>
            {yearremoved !== null && yearremoved !== 0 ? (
              <Text sx={{ fontWeight: 'bold', fontSize: 1 }}>
                Removed / mitigated in {yearremoved}
              </Text>
            ) : (
              <Flex sx={{ alignItems: 'baseline', gap: '0.25rem' }}>
                <Text sx={{ fontWeight: 'bold', fontSize: 1 }}>
                  Removed / mitigated
                </Text>
                <Text sx={{ fontSize: 0 }}>(year unknown)</Text>
              </Flex>
            )}
          </Flex>
        ) : null}

        {isPriority && !removed ? (
          <Flex
            sx={{
              alignItems: 'center',
              gap: '0.5rem',
              mt: '0.25rem',
            }}
          >
            <Box sx={{ color: 'blue.8' }}>
              <Fish size="1.5em" style={{ transform: 'rotate(180deg)' }} />
            </Box>
            <Text sx={{ fontWeight: 'bold', lineHeight: 1, fontSize: 1 }}>
              Identified as a priority by resource managers
            </Text>
          </Flex>
        ) : null}

        {isSurveyed ? (
          <Flex
            sx={{
              alignItems: 'center',
              gap: '0.5rem',
              mt: '0.25rem',
            }}
          >
            <Box sx={{ color: 'highlight' }}>
              <DraftingCompass size="1em" />
            </Box>
            <Text
              sx={{
                color: 'highlight',
                fontWeight: 'bold',
                lineHeight: 1,
                fontSize: 1,
              }}
            >
              Likely surveyed{' '}
              <Text
                sx={{ display: 'inline', fontSize: 0, fontWeight: 'normal' }}
              >
                (close to a surveyed barrier)
              </Text>
            </Text>
          </Flex>
        ) : null}
      </Box>
      <Button variant="close" onClick={onClose}>
        &#10006;
      </Button>
    </Flex>

    <Flex sx={{ color: 'grey.8', fontSize: 1, lineHeight: 1.1 }}>
      <Text sx={{ flex: '1 1 auto', mr: '1rem' }}>
        {!isEmptyString(state) ? `${county} County, ${STATES[state]}` : ''}
      </Text>

      <Text sx={{ flex: '0 0 auto', textAlign: 'right' }}>
        {formatNumber(lat, 3)}
        &deg; N, {formatNumber(lon, 3)}
        &deg; E
      </Text>
    </Flex>

    {/* Only show report for dams / small barriers */}
    {barrierType === 'dams' || barrierType === 'small_barriers' ? (
      <Box sx={{ lineHeight: 1, mt: '1.5rem' }}>
        <a
          href={`/report/${
            networkType === 'small_barriers' ? 'combined_barriers' : networkType
          }/${sarpid}`}
          target="_blank"
          rel="noreferrer"
          style={{ display: 'inline-block' }}
        >
          <Flex
            sx={{
              alignItems: 'baseline',
            }}
          >
            <Box sx={{ flex: '0 0 auto', color: 'link', mr: '0.25rem' }}>
              <FileDownload size="1em" />
            </Box>
            <Text>Create PDF report</Text>
          </Flex>
        </a>
      </Box>
    ) : null}
  </Box>
)

Header.propTypes = {
  barrierType: PropTypes.string.isRequired,
  networkType: PropTypes.string.isRequired,
  sarpid: PropTypes.string.isRequired,
  name: PropTypes.string,
  county: PropTypes.string,
  state: PropTypes.string,
  lat: PropTypes.number.isRequired,
  lon: PropTypes.number.isRequired,
  removed: PropTypes.bool,
  yearremoved: PropTypes.number,
  isPriority: PropTypes.bool,
  isSurveyed: PropTypes.bool,
  onClose: PropTypes.func.isRequired,
}

Header.defaultProps = {
  name: '',
  county: '',
  state: '',
  removed: false,
  yearremoved: null,
  isPriority: false,
  isSurveyed: false,
}

export default Header

// ui/src/lib/components/sidebar/barrierdetails/Header.svelte
<script lang="ts">
	import PriorityBarrierIcon from '@lucide/svelte/icons/map-plus'
	import RemovedBarrierIcon from '@lucide/svelte/icons/waves'
	import SurveyedIcon from '@lucide/svelte/icons/drafting-compass'
	import CloseIcon from '@lucide/svelte/icons/circle-x'
	import ReportIcon from '@lucide/svelte/icons/file-input'

	import { resolve } from '$app/paths'
	import { Button } from '$lib/components/ui/button'
	import { STATES } from '$lib/config/constants'
	import { formatNumber } from '$lib/util/format'

	import { isEmptyString } from '$lib/util/string'

	const {
		barrierType,
		networkType,
		sarpid,
		name,
		county,
		state,
		lat,
		lon,
		removed,
		yearremoved,
		isPriority,
		isSurveyed,
		onClose
	} = $props()
</script>

<div class="py-2 px-2 border-b-4 border-b-blue-2">
	<div class="flex justify-between">
		<div class="flex-auto">
			<div class="text-lg font-bold">
				{name}
			</div>
			{#if removed}
				<div class="flex mt-1 gap-2 items-center">
					<RemovedBarrierIcon class="text-blue-8 size-5" />
				</div>
				{#if yearremoved && yearremoved !== 0}
					<div class="text-sm font-bold">Removed / mitigated in {yearremoved}</div>
				{:else}
					<div class="font-bold font-sm">
						Removed / mitigated
						<span class="text-xs font-normal">(year unknown)</span>
					</div>
				{/if}
			{:else if isPriority}
				<div class="flex items-center gap-2 mt-1">
					<PriorityBarrierIcon class="text-blue-8 size-5" />
					<div class="font-bold">Identified as a priority by resource managers</div>
				</div>
			{/if}

			{#if isSurveyed}
				<div class="flex items-center mt-1 gap-2">
					<SurveyedIcon class="size-5" />
					<div class="font-bold text-sm">
						Likely surveyed
						<span class="text-xs font-normal"> (close to a surveyed barrier) </span>
					</div>
				</div>
			{/if}
		</div>
		<Button
			variant="ghost"
			onclick={onClose}
			class="p-0 flex-none"
			aria-label="close barrier details"><CloseIcon class="size-5" /></Button
		>
	</div>

	<div class="flex text-muted-foreground text-sm">
		<div class="flex-auto">
			{!isEmptyString(state) ? `${county} County, ${STATES[state as keyof typeof STATES]}` : ''}
		</div>
		<div class="flex-none text-right">
			{formatNumber(lat, 3)}
			&deg; N, {formatNumber(lon, 3)}
			&deg; E
		</div>
	</div>

	{#if barrierType === 'dams' || barrierType === 'small_barriers'}
		<a
			href={resolve(
				`/report/${networkType === 'small_barriers' ? 'combined_barriers' : networkType}/${sarpid}`,
				{ id: sarpid }
			)}
			target="_blank"
			class="block mt-6"
		>
			<div class="flex items-baseline">
				<ReportIcon class="size-5" />
				<div>Create PDF report</div>
			</div>
		</a>
	{/if}
</div>
