// ui/src/components/Workflow/StartOverButton.jsx
import React, { useState, memo } from 'react'
import PropTypes from 'prop-types'
import { Trash } from '@emotion-icons/fa-solid'
import { Button } from 'theme-ui'

import Confirm from 'components/Confirm'

const StartOverButton = ({ onStartOver }) => {
  const [confirmIsActive, setConfirmIsActive] = useState(false)

  const handleConfirm = () => {
    setConfirmIsActive(false)
    onStartOver()
  }

  const handleClick = () => {
    setConfirmIsActive(true)
  }

  return (
    <>
      {confirmIsActive && (
        <Confirm
          title="Start Over?"
          onConfirm={handleConfirm}
          onClose={() => setConfirmIsActive(false)}
        >
          You will lose all your work. Are you sure?
        </Confirm>
      )}

      <Button
        variant="warning"
        title="Start Over"
        onClick={handleClick}
        sx={{ mr: '1rem', fontSize: '1.1em' }}
      >
        <Trash size="1em" />
      </Button>
    </>
  )
}

StartOverButton.propTypes = {
  onStartOver: PropTypes.func.isRequired,
}

export default memo(StartOverButton)

// ui/src/lib/components/workflow/StartOverButton.svelte
<script lang="ts">
	import TrashIcon from '@lucide/svelte/icons/trash-2'

	import {
		Root as AlertDialog,
		Trigger,
		Content,
		Header,
		Title,
		Description,
		Footer,
		Cancel,
		Action
	} from '$lib/components/ui/alert-dialog'
	import { buttonVariants } from '$lib/components/ui/button'

	const { onStartOver } = $props()
</script>

<AlertDialog>
	<Trigger class={buttonVariants({ variant: 'destructive' })} title="Start over">
		<TrashIcon class="size-5" />
	</Trigger>
	<Content>
		<Header>
			<Title class="text-xl">Start over?</Title>
			<Description class="text-lg pb-4">You will lose all your work. Are you sure?</Description>
		</Header>
		<Footer class="justify-between sm:justify-between border-t border-t-grey-2 pt-4">
			<Cancel class={buttonVariants({ variant: 'default' })}>No</Cancel>
			<Action class={buttonVariants({ variant: 'destructive' })} onclick={onStartOver}>Yes</Action>
		</Footer>
	</Content>
</AlertDialog>
