// ui/src/components/Priority/UnitListItem.jsx
/* eslint-disable camelcase */
import React, { memo } from 'react'
import PropTypes from 'prop-types'
import { Box, Flex, Button, Text } from 'theme-ui'
import { ExclamationTriangle } from '@emotion-icons/fa-solid'

import { useBarrierType } from 'components/Data'
import { STATE_FIPS, STATES, barrierTypeLabels } from 'config'
import { formatNumber, pluralize } from 'util/format'

const SummaryUnitListItem = ({ layer, unit, onDelete }) => {
  const {
    id,
    ranked_dams: rankedDams = 0,
    total_small_barriers: totalSmallBarriers = 0,
    ranked_small_barriers: rankedSmallBarriers = 0,
    crossings = 0,
  } = unit
  let { name = id } = unit

  const insufficientBarriers = totalSmallBarriers < 10 && crossings > 10

  if (layer === 'State') {
    name = STATES[id]
  }

  const barrierType = useBarrierType()

  let count = 0
  let warning = null
  let countMessage = null

  switch (barrierType) {
    case 'dams': {
      count = rankedDams
      if (rankedDams === 0) {
        warning = 'no dams available for prioritization'
      } else {
        countMessage = `${formatNumber(rankedDams)} ${pluralize(
          'dam',
          rankedDams
        )}`
      }

      break
    }
    case 'small_barriers': {
      count = rankedSmallBarriers
      if (totalSmallBarriers === 0) {
        warning = `no potential road-related barriers have been assessed in this area (${formatNumber(
          crossings
        )} road / stream ${pluralize('crossing', crossings)})`
      } else if (rankedSmallBarriers === 0) {
        warning = `no road-related barriers available for prioritization (${formatNumber(
          crossings
        )} road / stream ${pluralize('crossing', crossings)})`
      } else if (insufficientBarriers) {
        const prefix =
          totalSmallBarriers === 0
            ? 'no potential road-related barriers'
            : `${formatNumber(
                totalSmallBarriers
              )} potential road-related ${pluralize(
                'barrier',
                totalSmallBarriers
              )} (${formatNumber(rankedSmallBarriers)} likely ${pluralize(
                'barrier',
                rankedSmallBarriers
              )})`
        warning = `${prefix} ${
          rankedSmallBarriers === 1 ? 'has' : 'have'
        } been assessed out of ${formatNumber(
          crossings
        )} road / stream ${pluralize(
          'crossing',
          crossings
        )}; this may not result in useful priorities`
      } else {
        countMessage = `${formatNumber(rankedSmallBarriers)} ${pluralize(
          'likely barrier',
          rankedSmallBarriers
        )} of ${formatNumber(
          totalSmallBarriers
        )} assessed potential road-related ${pluralize(
          'barrier',
          totalSmallBarriers
        )} (${formatNumber(crossings)} road/stream ${pluralize(
          'crossing',
          crossings
        )})`
      }

      break
    }
    case 'combined_barriers': {
      count = rankedDams + rankedSmallBarriers
      if (count === 0) {
        warning = `no ${barrierTypeLabels[barrierType]} available for prioritization`
      } else if (rankedDams > 0 && insufficientBarriers) {
        const prefix =
          totalSmallBarriers === 0
            ? 'no potential road-related barriers'
            : `${formatNumber(
                totalSmallBarriers
              )} potential road-related ${pluralize(
                'barrier',
                totalSmallBarriers
              )} (${formatNumber(rankedSmallBarriers)} likely ${pluralize(
                'barrier',
                rankedSmallBarriers
              )})`
        warning = `${prefix} ${
          rankedSmallBarriers === 1 ? 'has' : 'have'
        } been assessed out of ${formatNumber(
          crossings
        )} road / stream ${pluralize(
          'crossing',
          crossings
        )}; this may not result in useful priorities`

        countMessage = `${formatNumber(rankedDams)} ${pluralize(
          'dam',
          rankedDams
        )}`
      } else if (rankedDams > 0) {
        countMessage = `${formatNumber(rankedDams)} ${pluralize(
          'dam',
          rankedDams
        )} and ${formatNumber(rankedSmallBarriers)} ${pluralize(
          'likely barrier',
          rankedSmallBarriers
        )} of ${formatNumber(
          totalSmallBarriers
        )} assessed potential road-related ${pluralize(
          'barrier',
          totalSmallBarriers
        )} (${formatNumber(crossings)} road/stream ${pluralize(
          'crossing',
          crossings
        )})`
      }

      break
    }
    default: {
      break
    }
  }

  const handleDelete = () => onDelete(unit)

  return (
    <Flex
      as="li"
      sx={{
        justifyContent: 'space-between',
        borderBottom: '1px solid',
        borderBottomColor: 'grey.1',
        mx: '-1rem',
        px: '1rem',
        py: '0.5em',
        '&:first-of-type': {
          borderTop: '1px solid',
          borderTopColor: 'grey.1',
        },
      }}
    >
      <Box
        sx={{
          flex: '1 1 auto',
          mr: '1em',
        }}
      >
        <Text
          sx={{
            fontSize: '1rem',
            fontWeight: count > 0 ? 'bold' : 'inherit',
            fontStyle: count === 0 ? 'italic' : 'inherit',
            color: count === 0 ? 'grey.8' : 'inherit',
          }}
        >
          {name}
          {layer === 'County' ? ` County, ${STATE_FIPS[id.slice(0, 2)]}` : null}
        </Text>

        {layer === 'HUC6' || layer === 'HUC8' || layer === 'HUC12' ? (
          <Text
            sx={{
              fontSize: '0.9rem',
              fontStyle: count === 0 ? 'italic' : 'inherit',
              color: count === 0 ? 'grey.8' : 'inherit',
            }}
          >
            {layer}: {id}
          </Text>
        ) : null}

        {countMessage !== null ? (
          <Text variant="help">{countMessage}</Text>
        ) : null}

        {warning !== null ? (
          <Flex
            sx={{
              mt: '0.25rem',
              color: 'highlight',
              fontSize: 1,
              gap: '0.5rem',
              lineHeight: 1.1,
            }}
          >
            <Box sx={{ flex: '0 0 auto' }}>
              <ExclamationTriangle size="1.5em" />
            </Box>
            <Text sx={{ flex: '1 1 auto' }}>{warning}</Text>
          </Flex>
        ) : null}
      </Box>

      <Button variant="close" onClick={handleDelete}>
        &#10006;
      </Button>
    </Flex>
  )
}
SummaryUnitListItem.propTypes = {
  layer: PropTypes.string.isRequired,
  unit: PropTypes.object.isRequired,
  onDelete: PropTypes.func.isRequired,
}

export default memo(SummaryUnitListItem)

// ui/src/lib/components/workflow/UnitListItem.svelte
<script lang="ts">
	import CloseIcon from '@lucide/svelte/icons/circle-x'
	import WarningIcon from '@lucide/svelte/icons/triangle-alert'

	import { STATE_FIPS, STATES, barrierTypeLabels } from '$lib/config/constants'
	import { Button } from '$lib/components/ui/button'
	import type { BarrierTypePlural } from '$lib/config/types'
	import { formatNumber, pluralize } from '$lib/util/format'
	import { cn } from '$lib/utils'

	const { barrierType, layer, unit, onDelete, onZoomBounds } = $props()

	const {
		id,
		bbox = null,
		rankedDams = 0,
		totalSmallBarriers = 0,
		rankedSmallBarriers = 0,
		rankedLargefishBarriersDams = 0,
		rankedLargefishBarriersSmallBarriers = 0,
		rankedSmallfishBarriersDams = 0,
		rankedSmallfishBarriersSmallBarriers = 0,
		totalRoadCrossings = 0,
		unsurveyedRoadCrossings = 0
	} = $derived(unit)

	const name = $derived.by(() => {
		if (layer === 'State') {
			return STATES[id as keyof typeof STATES]
		}
		if (layer === 'County') {
			return `${unit.name}, ${STATE_FIPS[id.slice(0, 2) as keyof typeof STATE_FIPS]}`
		}

		return unit.name || id
	})

	const totalRoadBarriers = $derived(totalSmallBarriers + unsurveyedRoadCrossings)
	const insufficientBarriers = $derived(totalSmallBarriers < 10 && totalRoadBarriers > 10)

	const {
		count = 0,
		warning = null,
		countMessage = null
	} = $derived.by(() => {
		switch (barrierType) {
			case 'dams': {
				if (rankedDams === 0) {
					return {
						count: rankedDams,
						warning: 'no dams available for prioritization'
					}
				}
				return {
					count: rankedDams,
					countMessage: `${formatNumber(rankedDams)} ${pluralize('dam', rankedDams)}`
				}
			}
			case 'small_barriers': {
				if (totalSmallBarriers === 0) {
					return {
						count: totalSmallBarriers,
						warning: `no road/stream crossings (potential barriers) have been assessed in this area (${formatNumber(
							totalRoadBarriers
						)} road / stream ${pluralize('crossing', totalRoadBarriers)})`
					}
				} else if (rankedSmallBarriers === 0) {
					return {
						count: totalSmallBarriers,
						warning: `no road-related barriers available for prioritization (${formatNumber(
							totalRoadBarriers
						)} road / stream ${pluralize('crossing', totalRoadBarriers)})`
					}
				} else if (insufficientBarriers) {
					const prefix =
						totalSmallBarriers === 0
							? 'no road/stream crossings (potential barriers)'
							: `${formatNumber(totalSmallBarriers)} road/stream ${pluralize(
									'crossing',
									totalSmallBarriers
								)} (${formatNumber(rankedSmallBarriers)} likely ${pluralize(
									'barrier',
									rankedSmallBarriers
								)})`

					return {
						count: totalSmallBarriers,
						warning: `${prefix} ${
							rankedSmallBarriers === 1 ? 'has' : 'have'
						} been assessed out of ${formatNumber(totalRoadBarriers)} total road / stream ${pluralize(
							'crossing',
							totalRoadBarriers
						)}; this may not result in useful priorities`
					}
				}
				return {
					count: totalSmallBarriers,
					countMessage: `${formatNumber(rankedSmallBarriers)} ${pluralize(
						'barrier',
						rankedSmallBarriers
					)} (${formatNumber(totalSmallBarriers)} assessed road/stream ${pluralize(
						'crossing',
						totalSmallBarriers
					)} of ${formatNumber(totalRoadBarriers)} total road/stream ${pluralize(
						'crossing',
						totalRoadBarriers
					)})`
				}
			}
			case 'combined_barriers':
			case 'largefish_barriers':
			case 'smallfish_barriers': {
				// extract counts specific to network type
				let rankedD = 0
				let rankedSB = 0
				if (barrierType === 'combined_barriers') {
					rankedD = rankedDams
					rankedSB = rankedSmallBarriers
				} else if (barrierType === 'largefish_barriers') {
					rankedD = rankedLargefishBarriersDams
					rankedSB = rankedLargefishBarriersSmallBarriers
				} else if (barrierType === 'smallfish_barriers') {
					rankedD = rankedSmallfishBarriersDams
					rankedSB = rankedSmallfishBarriersSmallBarriers
				}

				const rankedCount = rankedD + rankedSB

				if (rankedCount === 0) {
					return {
						count: rankedCount,
						warning: `no ${barrierTypeLabels[barrierType as BarrierTypePlural]} available for prioritization`
					}
				} else if (rankedD > 0 && insufficientBarriers) {
					const prefix =
						totalSmallBarriers === 0
							? 'no assessed road/stream crossings'
							: `${formatNumber(totalSmallBarriers)} assessed road/stream ${pluralize(
									'crossing',
									totalSmallBarriers
								)} (${formatNumber(rankedSB)} likely ${pluralize('barrier', rankedSB)})`
					return {
						count: rankedCount,
						warning: `${prefix} ${
							totalSmallBarriers === 1 ? 'has' : 'have'
						} been assessed out of ${formatNumber(totalRoadBarriers)} total road / stream ${pluralize(
							'crossing',
							totalRoadBarriers
						)}; this may not result in useful priorities`,

						countMessage: `${formatNumber(rankedD)} ${pluralize('dam', rankedD)}`
					}
				} else if (rankedD > 0) {
					return {
						count: rankedCount,
						countMessage: `${formatNumber(rankedD)} ${pluralize(
							'dam',
							rankedDams
						)} and ${formatNumber(rankedSB)} road-related ${pluralize(
							'barrier',
							rankedSB
						)} (${formatNumber(totalSmallBarriers)} assessed road/stream ${pluralize(
							'crossing',
							totalSmallBarriers
						)} of ${formatNumber(totalRoadBarriers)} total road/stream ${pluralize(
							'crossing',
							totalRoadBarriers
						)})`
					}
				}

				break
			}
			case 'road_crossings': {
				if (totalRoadCrossings === 0) {
					return {
						count: totalRoadCrossings,
						warning: `no road/stream crossings have been mapped in this area`
					}
				}
				return {
					count: totalRoadCrossings,
					countMessage: `${formatNumber(totalRoadCrossings)} road/stream ${pluralize(
						'crossing',
						totalRoadCrossings
					)} (${formatNumber(
						unsurveyedRoadCrossings
					)} have not yet been surveyed; ${formatNumber(totalSmallBarriers)} potential road-related ${pluralize('barrier', totalSmallBarriers)} have been inventoried)`
				}
			}
		}
		return {}
	})
</script>

<li
	class="grid grid-cols-[1fr_3.5rem] gap-2 border-b border-b-grey-1 -mx-4 px-4 py-2 first-of-type:border-t first-of-type:border-t-grey-1"
>
	<div>
		<div
			class={cn('text-base', {
				'font-bold': count > 0,
				'italic text-muted-foreground': count === 0
			})}
		>
			{name}
		</div>

		{#if layer.startsWith('HUC')}
			<div
				class={cn('text-xs', {
					'italic text-muted-foreground': count === 0
				})}
			>
				{layer}: {id}
			</div>
		{/if}

		{#if countMessage}
			<div class="text-sm text-muted-foreground mt-0.5">
				{countMessage}
			</div>
		{/if}

		{#if warning}
			<div class="flex mt-1 text-destructive text-sm gap-2 leading-tight">
				<WarningIcon class="size-4 flex-none" />
				<div class="flex-auto">
					{warning}
				</div>
			</div>
		{/if}
	</div>
	<div class="flex flex-none flex-col gap-2 items-end">
		<Button variant="close" onclick={() => onDelete(unit)} aria-label={`remove ${name} from list`}
			><CloseIcon class="size-5" />
		</Button>

		{#if bbox}
			<Button
				variant="link"
				class="text-right p-0! h-auto flex-none text-xs no-underline hover:no-underline"
				onclick={() => onZoomBounds(bbox)}
			>
				zoom to
			</Button>
		{/if}
	</div>
</li>
