// ui/src/lib/components/report/Header.svelte
<script lang="ts">
	import PriorityBarrierIcon from '@lucide/svelte/icons/map-plus'
	import RemovedBarrierIcon from '@lucide/svelte/icons/waves'

	import { barrierTypeLabelSingular, STATES } from '$lib/config/constants'
	import { formatNumber } from '$lib/util/format'

	const {
		barrierType,
		name,
		county,
		state,
		lat,
		lon,
		removed,
		yearremoved,
		yearsurveyed,
		resurveyed,
		ispriority,
		lowheaddam,
		diversion,
		invasive,
		estimated
	} = $props()

	const barrierTypeLabel = $derived.by(() => {
		let defaultLabel =
			barrierTypeLabelSingular[barrierType as keyof typeof barrierTypeLabelSingular]
		if (estimated) {
			defaultLabel = `estimated ${defaultLabel}`
		}

		const labelParts = []
		if (lowheaddam === 1) {
			labelParts.push('lowhead dam')
		} else if (lowheaddam === 2) {
			labelParts.push('likely lowhead dam')
		}
		if (diversion === 2) {
			labelParts.push('likely water diversion')
		} else if (diversion >= 1) {
			labelParts.push('water diversion')
		}

		if (labelParts.length === 0) {
			labelParts.push(defaultLabel)
		}

		if (invasive) {
			labelParts.push('invasive species barrier')
		}

		return labelParts.join(', ')
	})
</script>

<div class="leading-tight">
	<h1 class="font-bold text-xl sm:text-[1.75rem] leading-tight">{name}</h1>
	{#if removed}
		<div class="flex items-center gap-2 mt-1 mb-4">
			<RemovedBarrierIcon class="text-blue-8 size-5" />
			<div class="font-bold">
				Removed / mitigated
				{yearremoved !== null && yearremoved !== 0 ? `in ${yearremoved}` : `(year unknown)`}
			</div>
		</div>
	{:else if ispriority}
		<div class="flex items-center gap-2 mt-1 mb-4">
			<PriorityBarrierIcon class="text-blue-8 size-5" />
			<div class="font-bold">Identified as a priority by resource managers</div>
		</div>
	{/if}

	<div class="flex flex-wrap text-muted-foreground justify-between gap-2 sm:gap-8 mt-2">
		<div class="flex-auto">
			Barrier type: {barrierTypeLabel}
		</div>

		{#if yearsurveyed !== 0}
			<div class="flex-none">
				Surveyed in {yearsurveyed}
				{resurveyed !== 0 ? ' (resurveyed)' : null}
			</div>
		{/if}
	</div>

	<div class="flex flex-wrap justify-between gap-2 sm:gap-8 mt-4 text-muted-foreground">
		<div class="flex-auto">
			{county} County, {STATES[state as keyof typeof STATES]}
		</div>
		<div class="flex-none">
			Located at {formatNumber(lat, 5)}
			&deg; N / {formatNumber(lon, 5)}
			&deg; E
		</div>
	</div>
</div>

// ui/src/components/ReportPreview/Header.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Fish, Water } from '@emotion-icons/fa-solid'
import { Box, Flex, Text } from 'theme-ui'

import { barrierTypeLabelSingular, STATES } from 'config'
import { formatNumber } from 'util/format'

const Header = ({
  barrierType,
  name,
  county,
  state,
  lat,
  lon,
  removed,
  yearremoved,
  yearsurveyed,
  resurveyed,
  ispriority,
  lowheaddam,
  diversion,
  invasive,
  estimated,
}) => {
  const barrierTypeLabel = barrierTypeLabelSingular[barrierType]
  const isLowheadDam = lowheaddam === 1 || lowheaddam === 2
  const isDiversion = diversion !== null && diversion >= 1

  return (
    <Flex sx={{ alignItems: 'flex-end', mb: ' 0.5rem', lineHeight: 1.2 }}>
      <Box sx={{ flex: '1 1 auto' }}>
        <Text sx={{ fontSize: '2rem', fontWeight: 'bold' }}>{name}</Text>
        {removed ? (
          <Flex
            sx={{
              alignItems: 'center',
              gap: '0.5rem',
              mt: '0.25rem',
              mb: '1rem',
            }}
          >
            <Box sx={{ color: 'blue.8', mb: '2px' }}>
              <Water size="1em" />
            </Box>

            <Text sx={{ fontWeight: 'bold' }}>
              Removed / mitigated{' '}
              {yearremoved !== null && yearremoved !== 0
                ? `in ${yearremoved}`
                : `(year unknown)`}
            </Text>
          </Flex>
        ) : null}

        {ispriority && !removed ? (
          <Flex
            sx={{
              alignItems: 'center',
              gap: '0.5rem',
              mt: '0.25rem',
              mb: '1rem',
            }}
          >
            <Box sx={{ color: 'blue.8' }}>
              <Fish size="1.5em" style={{ transform: 'rotate(180deg)' }} />
            </Box>
            <Text sx={{ fontWeight: 'bold' }}>
              Identified as a priority by resource managers
            </Text>
          </Flex>
        ) : null}

        <Flex sx={{ color: 'grey.8', justifyContent: 'space-between' }}>
          <Box sx={{ flex: '1 1 auto' }}>
            Barrier type:{' '}
            {isLowheadDam ? (
              <>
                {lowheaddam === 2 ? 'likely ' : null}
                lowhead dam
              </>
            ) : null}
            {isDiversion ? (
              <>
                {isLowheadDam ? ',' : null} {diversion === 2 ? 'likely ' : null}{' '}
                water diversion
              </>
            ) : null}
            {estimated ? 'estimated ' : ''}
            {!(isLowheadDam || isDiversion) ? barrierTypeLabel : null}
            {invasive ? <>, invasive species barrier</> : null}
          </Box>
          {yearsurveyed !== 0 ? (
            <Box sx={{ flex: '0 0 auto' }}>
              surveyed in {yearsurveyed}
              {resurveyed !== 0 ? ' (resurveyed)' : null}
            </Box>
          ) : null}
        </Flex>

        <Flex sx={{ justifyContent: 'space-between', mt: '0.5rem' }}>
          <Text sx={{ flex: '1 1 auto', color: 'grey.8' }}>
            {county} County, {STATES[state]}
          </Text>
          <Text sx={{ flex: '0 0 auto', color: 'grey.8' }}>
            Located at {formatNumber(lat, 5)}
            &deg; N / {formatNumber(lon, 5)}
            &deg; E
          </Text>
        </Flex>
      </Box>
    </Flex>
  )
}

Header.propTypes = {
  barrierType: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  county: PropTypes.string.isRequired,
  state: PropTypes.string.isRequired,
  lat: PropTypes.number.isRequired,
  lon: PropTypes.number.isRequired,
  removed: PropTypes.bool,
  resurveyed: PropTypes.number,
  yearremoved: PropTypes.number,
  yearsurveyed: PropTypes.number,
  ispriority: PropTypes.number,
  lowheaddam: PropTypes.number,
  diversion: PropTypes.number,
  invasive: PropTypes.bool,
  estimated: PropTypes.bool,
}

Header.defaultProps = {
  removed: false,
  resurveyed: 0,
  yearremoved: null,
  yearsurveyed: 0,
  ispriority: 0,
  lowheaddam: 0,
  diversion: 0,
  invasive: false,
  estimated: false,
}

export default Header
