// ui/src/lib/components/report/LandscapeContext.svelte
<script lang="ts">
	import {
		FISH_HABITAT_PARTNERSHIPS,
		STATES,
		TNC_COLDWATER_STATUS,
		TNC_RESILIENCE,
		TU_BROOK_TROUT_PORTFOLIO
	} from '$lib/config/constants'

	const {
		brooktroutportfolio,
		cold,
		congressionaldistrict,
		ejtract,
		ejtribal,
		fishhabitatpartnership,
		nativeterritories,
		resilience
	} = $props()
</script>

<section>
	<h2>Landscape context</h2>

	<div class="report-entries">
		{#if cold}
			<div>
				Ability of the watershed to maintain cold water habitat:
				{TNC_COLDWATER_STATUS[cold as keyof typeof TNC_COLDWATER_STATUS]}
				<div class="text-xs text-muted-foreground leading-tight">
					based on The Nature Conservancy's cold water temperature score where this barrier occurs
					(TNC; March 2024).
				</div>
			</div>
		{/if}

		{#if resilience}
			<div>
				Freshwater resilience: {TNC_RESILIENCE[resilience as keyof typeof TNC_RESILIENCE]}
				<div class="text-xs text-muted-foreground leading-tight">
					based on the The Nature Conservancy&apos;s freshwater resilience category of the watershed
					where this barrier occurs (v0.44).
				</div>
			</div>
		{/if}

		{#if brooktroutportfolio}
			Eastern brook trout conservation portfolio:
			{TU_BROOK_TROUT_PORTFOLIO[brooktroutportfolio as keyof typeof TU_BROOK_TROUT_PORTFOLIO]}
			<div class="text-xs text-muted-foreground leading-tight">
				based on the
				<a
					href="https://www.tu.org/science/conservation-planning-and-assessment/conservation-portfolio/"
					target="_blank"
					rel="external"
				>
					brook trout conservation portfolio
				</a>
				category of the watershed where this barrier occurs, as identified by Trout Unlimited (7/4/2022).
			</div>
		{/if}

		{#if ejtract || ejtribal}
			<div>
				Climate and environmental justice:
				{ejtract ? 'within a disadvantaged census tract' : null}
				{ejtract && ejtribal ? ', ' : null}
				{ejtribal ? 'within a tribal community' : null}
			</div>
		{/if}

		{#if nativeterritories}
			<div>
				Within the following native territories: {nativeterritories}
				<div class="text-xs text-muted-foreground leading-tight">
					based on data provided by
					<a href="https://native-land.ca/"> Native Land Digital </a>.
				</div>
			</div>
		{/if}

		{#if congressionaldistrict}
			<div>
				Congressional district (119th congress):
				{STATES[congressionaldistrict.slice(0, 2) as keyof typeof STATES]} Congressional District
				{congressionaldistrict.slice(2)}
			</div>
		{/if}

		{#if fishhabitatpartnership}
			<div>
				Fish Habitat Partnerships working in this area:
				<div class="mt-1 ml-4">
					{#each fishhabitatpartnership.split(',') as fhp, i (fhp)}
						<a
							href={FISH_HABITAT_PARTNERSHIPS[fhp as keyof typeof FISH_HABITAT_PARTNERSHIPS].url}
							target="_blank"
							rel="external"
						>
							{FISH_HABITAT_PARTNERSHIPS[fhp as keyof typeof FISH_HABITAT_PARTNERSHIPS].name}
						</a>
					{/each}
				</div>
			</div>
		{/if}
	</div>
</section>

// ui/src/components/ReportPreview/LandscapeContext.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Box, Heading, Text } from 'theme-ui'

import {
  FISH_HABITAT_PARTNERSHIPS,
  STATES,
  TNC_COLDWATER_STATUS,
  TNC_RESILIENCE,
  TU_BROOK_TROUT_PORTFOLIO,
} from 'config'
import { OutboundLink } from 'components/Link'
import { Entry } from './elements'

const LandscapeContext = ({
  brooktroutportfolio,
  cold,
  congressionaldistrict,
  ejtract,
  ejtribal,
  fishhabitatpartnership,
  nativeterritories,
  resilience,
  sx,
}) => (
  <Box sx={sx}>
    <Heading as="h3">Landscape context</Heading>

    {cold ? (
      <Entry>
        Ability of the watershed to maintain cold water habitat:{' '}
        {TNC_COLDWATER_STATUS[cold]}
        <Text sx={{ fontSize: 0, color: 'grey.7', lineHeight: 1.1 }}>
          based on The Nature Conservancy&apos;s cold water temperature score
          where this barrier occurs (TNC; March 2024).
        </Text>
      </Entry>
    ) : null}

    {resilience ? (
      <Entry>
        Freshwater resilience: {TNC_RESILIENCE[resilience]}
        <Text sx={{ fontSize: 0, color: 'grey.7', lineHeight: 1.1 }}>
          based on the The Nature Conservancy&apos;s freshwater resilience
          category of the watershed where this barrier occurs (v0.44).
        </Text>
      </Entry>
    ) : null}

    {brooktroutportfolio ? (
      <Entry>
        Eastern brook trout conservation portfolio:{' '}
        {TU_BROOK_TROUT_PORTFOLIO[brooktroutportfolio]}
        <Text sx={{ fontSize: 0, color: 'grey.7', lineHeight: 1.1 }}>
          based on the{' '}
          <OutboundLink to="https://www.tu.org/science/conservation-planning-and-assessment/conservation-portfolio/">
            brook trout conservation portfolio
          </OutboundLink>{' '}
          category of the watershed where this barrier occurs, as identified by
          Trout Unlimited (7/4/2022).
        </Text>
      </Entry>
    ) : null}

    {ejtract || ejtribal ? (
      <Entry>
        Climate and environmental justice:{' '}
        {ejtract ? 'within a disadvantaged census tract' : null}
        {ejtract && ejtribal ? ', ' : null}
        {ejtribal ? 'within a tribal community' : null}
      </Entry>
    ) : null}

    {nativeterritories ? (
      <Entry>
        <Text>
          Within the following native territories: {nativeterritories}
        </Text>
        <Text sx={{ fontSize: 0, color: 'grey.7', lineHeight: 1.1 }}>
          based on data provided by{' '}
          <OutboundLink to="https://native-land.ca/">
            Native Land Digital
          </OutboundLink>
          .
        </Text>
      </Entry>
    ) : null}

    {congressionaldistrict ? (
      <Entry>
        Congressional district (118th congress):{' '}
        {STATES[congressionaldistrict.slice(0, 2)]} Congressional District{' '}
        {congressionaldistrict.slice(2)}
      </Entry>
    ) : null}

    {fishhabitatpartnership ? (
      <Entry>
        <Text>Fish Habitat Partnerships working in this area:</Text>
        <Text sx={{ mt: '0.25rem', ml: '1rem' }}>
          {fishhabitatpartnership.split(',').map((code, i) => (
            <React.Fragment key={code}>
              {i > 0 ? ', ' : null}
              <OutboundLink to={FISH_HABITAT_PARTNERSHIPS[code].url}>
                {FISH_HABITAT_PARTNERSHIPS[code].name}
              </OutboundLink>
            </React.Fragment>
          ))}
        </Text>
      </Entry>
    ) : null}
  </Box>
)

LandscapeContext.propTypes = {
  brooktroutportfolio: PropTypes.number,
  cold: PropTypes.number,
  congressionaldistrict: PropTypes.string,
  ejtract: PropTypes.bool,
  ejtribal: PropTypes.bool,
  fishhabitatpartnership: PropTypes.string,
  nativeterritories: PropTypes.string,
  resilience: PropTypes.number,
  sx: PropTypes.object,
}

LandscapeContext.defaultProps = {
  brooktroutportfolio: null,
  cold: null,
  congressionaldistrict: null,
  ejtract: false,
  ejtribal: false,
  fishhabitatpartnership: null,
  nativeterritories: null,
  resilience: null,
  sx: null,
}

export default LandscapeContext
