// ui/src/lib/components/report/MarineConnectivity.svelte
<script lang="ts">
	import { formatNumber, pluralize } from '$lib/util/format'

	const {
		barrierType,
		milestooutlet,
		totaldownstreamdams,
		totaldownstreamsmallbarriers,
		totaldownstreamwaterfalls
	} = $props()

	const numCols = $derived(
		1 +
			Number(totaldownstreamdams >= 0) +
			Number(barrierType === 'small_barriers' && totaldownstreamsmallbarriers >= 0) +
			Number(totaldownstreamwaterfalls >= 0)
	)
</script>

<section>
	<h2>Marine connectivity</h2>

	<div
		class={`grid sm:grid-cols-${numCols} gap-4 mt-4 leading-snug sm:[&>div]:py-2 sm:[&>div+div]:border-l sm:[&>div+div]:border-l-grey-2 sm:[&>div+div]:pl-4`}
	>
		<div>
			<b>{formatNumber(milestooutlet)}</b>
			{pluralize('mile', milestooutlet)} downstream to the ocean
		</div>

		{#if totaldownstreamdams >= 0}
			<div>
				<b>{formatNumber(totaldownstreamdams)}</b>
				{pluralize('dam', totaldownstreamdams)} downstream
			</div>
		{/if}

		{#if barrierType === 'small_barriers' && totaldownstreamsmallbarriers >= 0}
			<div>
				<b>{formatNumber(totaldownstreamsmallbarriers)}</b> assessed road-related {pluralize(
					'barrier',
					totaldownstreamsmallbarriers
				)}
				downstream
			</div>
		{/if}

		{#if totaldownstreamwaterfalls >= 0}
			<div>
				<b>{formatNumber(totaldownstreamwaterfalls)}</b>
				{pluralize('waterfall', totaldownstreamwaterfalls)} downstream
			</div>
		{/if}
	</div>
</section>

// ui/src/components/ReportPreview/MarineConnectivity.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Box, Heading, Grid } from 'theme-ui'

import { formatNumber, pluralize } from 'util/format'

const MarineConnectivity = ({
  barrierType,
  milestooutlet,
  totaldownstreamdams,
  totaldownstreamsmallbarriers,
  totaldownstreamwaterfalls,
  sx,
}) => {
  const numCols =
    1 +
    (totaldownstreamdams >= 0) +
    (barrierType === 'small_barriers' && totaldownstreamsmallbarriers >= 0) +
    (totaldownstreamwaterfalls >= 0)

  return (
    <Box sx={sx}>
      <Heading as="h3">Marine connectivity</Heading>
      <Grid
        columns={numCols}
        gap={0}
        sx={{
          mt: '1rem',
          '&>div': {
            py: '0.5em',
          },
          '&> div + div': {
            ml: '1rem',
            pl: '1rem',
            borderLeft: '1px solid',
            borderLeftColor: 'grey.3',
          },
        }}
      >
        <Box>
          <b>{formatNumber(milestooutlet)}</b>{' '}
          {pluralize('mile', milestooutlet)} downstream to the ocean
        </Box>
        {totaldownstreamdams >= 0 ? (
          <Box>
            <b>{formatNumber(totaldownstreamdams)}</b>{' '}
            {pluralize('dam', totaldownstreamdams)} downstream
          </Box>
        ) : null}
        {barrierType === 'small_barriers' &&
        totaldownstreamsmallbarriers >= 0 ? (
          <Box>
            <b>{formatNumber(totaldownstreamsmallbarriers)}</b> assessed
            road-related {pluralize('barrier', totaldownstreamsmallbarriers)}{' '}
            downstream
          </Box>
        ) : null}
        {totaldownstreamwaterfalls >= 0 ? (
          <Box>
            <b>{formatNumber(totaldownstreamwaterfalls)}</b>{' '}
            {pluralize('waterfall', totaldownstreamwaterfalls)} downstream
          </Box>
        ) : null}
      </Grid>
    </Box>
  )
}

MarineConnectivity.propTypes = {
  barrierType: PropTypes.string.isRequired,
  milestooutlet: PropTypes.number,
  totaldownstreamdams: PropTypes.number,
  totaldownstreamsmallbarriers: PropTypes.number,
  totaldownstreamwaterfalls: PropTypes.number,
  sx: PropTypes.object,
}

MarineConnectivity.defaultProps = {
  milestooutlet: 0,
  totaldownstreamdams: 0,
  totaldownstreamsmallbarriers: 0,
  totaldownstreamwaterfalls: 0,
  sx: null,
}

export default MarineConnectivity
