// ui/src/lib/components/map/Coords.svelte
<script lang="ts">
	type Coords = {
		lat: number
		lng: number
	}

	const { map } = $props()

	let coords: Coords | null = $state(null)

	$effect(() => {
		if (!map) {
			return
		}

		map.on('mousemove', ({ lngLat }: { lngLat: Coords }) => {
			coords = lngLat
		})

		map.on('mouseout', () => {
			coords = null
		})
	})
</script>

{#if coords !== null}
	<div class="absolute bottom-0 left-25 py-1 px-2 z-2000 bg-white/50 text-xs">
		{Math.round(coords.lat * 100000) / 100000}° N,
		{Math.round(coords.lng * 100000) / 100000}° E
	</div>
{/if}

// ui/src/components/map/Coords.jsx
import React, { useState, memo } from 'react'
import PropTypes from 'prop-types'

import styled from 'style'

const Wrapper = styled.div`
  position: absolute;
  bottom: 0px;
  left: 110px;
  padding: 4px 8px;
  z-index: 2000;
  background: rgba(255, 255, 255, 0.5);
  font-size: 0.75rem;
`

const Coords = ({ map }) => {
  const [{ lat, lng }, setCoords] = useState({})

  // Track mouse cursor and display coordinates
  map.on('mousemove', ({ lngLat }) => {
    setCoords(lngLat)
  })

  map.on('mouseout', () => {
    setCoords({})
  })

  return (
    lat !== undefined &&
    lng !== undefined && (
      <Wrapper>
        {Math.round(lat * 100000) / 100000}° N,&nbsp;
        {Math.round(lng * 100000) / 100000}° E
      </Wrapper>
    )
  )
}

Coords.propTypes = {
  map: PropTypes.object.isRequired,
}

export default memo(Coords)
