// ui/src/pages/priority/index.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { graphql } from 'gatsby'
import { Box, Grid, Heading, Flex, Button, Text, Paragraph } from 'theme-ui'
import { AngleDoubleRight } from '@emotion-icons/fa-solid'

import { useSummaryData } from 'components/Data'
import { Link } from 'components/Link'
import { Layout, SEO } from 'components/Layout'
import { HeaderImage } from 'components/Image'
import { formatNumber } from 'util/format'

const PrioritizePage = ({ data: { headerImage } }) => {
  const {
    rankedDams,
    rankedSmallBarriers,
    rankedLargefishBarriersDams,
    rankedLargefishBarriersSmallBarriers,
    rankedSmallfishBarriersDams,
    rankedSmallfishBarriersSmallBarriers,
  } = useSummaryData()

  return (
    <Layout>
      <HeaderImage
        image={headerImage.childImageSharp.gatsbyImageData}
        height="20vh"
        minHeight="12rem"
        credits={{
          author: 'Zach Dutra',
          url: 'https://unsplash.com/photos/2d7Y5Yi3aq8',
        }}
      />

      <Box sx={{ p: '2rem' }}>
        <Grid columns="1fr 2fr" gap={5}>
          <Box
            sx={{
              h4: {
                fontSize: '1.25rem',
              },
            }}
          >
            <Heading as="h3">How to prioritize barriers:</Heading>

            <Box sx={{ mt: '1rem' }}>
              <Flex sx={{ alignItems: 'center' }}>
                <Box variant="boxes.step">1</Box>
                <Heading as="h4" sx={{ flex: '1 1 auto' }}>
                  Select area of interest.
                </Heading>
              </Flex>
              <Paragraph variant="help" sx={{ ml: '3.75rem' }}>
                You can select areas using state, county, and watershed
                boundaries.
                <br />
                <br />
                Prioritization is limited to areas with dams or assessed
                barriers depending on the scenario.
              </Paragraph>
            </Box>

            <Box sx={{ mt: '1rem' }}>
              <Flex sx={{ alignItems: 'center' }}>
                <Box variant="boxes.step">2</Box>
                <Heading as="h4" sx={{ flex: '1 1 auto' }}>
                  Filter barriers.
                </Heading>
              </Flex>
              <Paragraph variant="help" sx={{ ml: '3.75rem' }}>
                You can filter barriers by feasibility, height, and other key
                characteristics to select those that best meet your needs.
              </Paragraph>
            </Box>

            <Box sx={{ mt: '1rem' }}>
              <Flex sx={{ alignItems: 'center' }}>
                <Box variant="boxes.step">3</Box>
                <Heading as="h4" sx={{ flex: '1 1 auto' }}>
                  Explore priorities on the map.
                </Heading>
              </Flex>
              <Paragraph variant="help" sx={{ ml: '3.75rem' }}>
                Once you have defined your area of interest and selected the
                barriers you want, you can explore them on the map.
              </Paragraph>
            </Box>

            <Box sx={{ mt: '1rem' }}>
              <Flex sx={{ alignItems: 'center' }}>
                <Box variant="boxes.step">4</Box>
                <Heading as="h4" sx={{ flex: '1 1 auto' }}>
                  Download prioritized barriers.
                </Heading>
              </Flex>
              <Paragraph variant="help" sx={{ ml: '3.75rem' }}>
                You can download the inventory for your area of interest and
                perform offline work.
              </Paragraph>
            </Box>
          </Box>

          <Box>
            <Heading as="h3" sx={{ mb: '1rem' }}>
              Prioritization scenarios available:
            </Heading>

            <Grid
              columns={[1, 2, 3]}
              gap={3}
              sx={{
                '&>div': {
                  border: '1px solid',
                  borderColor: 'grey.2',
                  borderRadius: '0.5rem',
                  boxShadow: '2px 2px 4px #EEE',
                  p: '1rem',
                },
                '& h4': {
                  borderBottom: '1px solid',
                  borderBottomColor: 'grey.9',
                  pb: '0.25rem',
                  mb: '0.5rem',
                },
              }}
            >
              <Flex sx={{ flexDirection: 'column' }}>
                <Box sx={{ flex: '1 1 auto', mb: '1rem' }}>
                  <Heading as="h4">Dams</Heading>
                  <Text sx={{ lineHeight: 1.2 }}>
                    Prioritize dams based on aquatic networks cut by dams and
                    waterfalls.
                  </Text>
                </Box>

                <Box sx={{ flex: '0 0 auto' }}>
                  <Link to="/priority/dams">
                    <Button sx={{ width: '100%', textAlign: 'left' }}>
                      <AngleDoubleRight
                        size="1.25rem"
                        style={{ marginRight: '0.5rem', marginTop: '-0.25rem' }}
                      />
                      Start prioritizing
                    </Button>
                  </Link>
                  <Text
                    sx={{
                      textAlign: 'center',
                      fontSize: 1,
                      color: 'grey.7',
                      mt: '0.5rem',
                    }}
                  >
                    {formatNumber(rankedDams)} available
                  </Text>
                </Box>
              </Flex>
              <Flex sx={{ flexDirection: 'column' }}>
                <Box sx={{ flex: '1 1 auto', mb: '1rem' }}>
                  <Heading as="h4">Road-related barriers</Heading>
                  <Text sx={{ lineHeight: 1.2 }}>
                    Prioritize road-related barriers based on aquatic networks
                    cut by dams, waterfalls, and road-related barriers with at
                    least moderate barrier severity.
                  </Text>
                </Box>
                <Box sx={{ flex: '0 0 auto' }}>
                  <Link to="/priority/small_barriers">
                    <Button sx={{ width: '100%', textAlign: 'left' }}>
                      <AngleDoubleRight
                        size="1.25rem"
                        style={{ marginRight: '0.5rem', marginTop: '-0.25rem' }}
                      />
                      Start prioritizing
                    </Button>
                  </Link>
                  <Text
                    sx={{
                      textAlign: 'center',
                      fontSize: 1,
                      color: 'grey.7',
                      mt: '0.5rem',
                    }}
                  >
                    {formatNumber(rankedSmallBarriers)} available
                  </Text>
                </Box>
              </Flex>
              <Flex sx={{ flexDirection: 'column' }}>
                <Box sx={{ flex: '1 1 auto', mb: '1rem' }}>
                  <Heading as="h4">Dams & road-related barriers</Heading>
                  <Text sx={{ lineHeight: 1.2 }}>
                    Prioritize dams and road-related barriers based on aquatic
                    networks cut by dams, waterfalls, and road-related barriers
                    with at least moderate barrier severity.
                  </Text>
                </Box>
                <Box sx={{ flex: '0 0 auto' }}>
                  <Link to="/priority/combined_barriers">
                    <Button sx={{ width: '100%', textAlign: 'left' }}>
                      <AngleDoubleRight
                        size="1.25rem"
                        style={{ marginRight: '0.5rem', marginTop: '-0.25rem' }}
                      />{' '}
                      Start prioritizing
                    </Button>
                  </Link>
                  <Text
                    sx={{
                      textAlign: 'center',
                      fontSize: 1,
                      color: 'grey.7',
                      mt: '0.5rem',
                    }}
                  >
                    {formatNumber(rankedDams + rankedSmallBarriers)} available
                  </Text>
                </Box>
              </Flex>

              <Flex sx={{ flexDirection: 'column' }}>
                <Box sx={{ flex: '1 1 auto', mb: '1rem' }}>
                  <Heading as="h4">Large-bodied fish barriers</Heading>
                  <Text sx={{ lineHeight: 1.2 }}>
                    Prioritize dams and road-related barriers that are likely to
                    impact large-bodied fish species based on aquatic networks
                    cut by dams and waterfalls that do not have partial or
                    seasonal passability to salmonids and non-salmonids, and
                    road-related barriers with severe or significant barrier
                    severity.
                  </Text>
                </Box>
                <Box sx={{ flex: '0 0 auto' }}>
                  <Link to="/priority/largefish_barriers">
                    <Button sx={{ width: '100%', textAlign: 'left' }}>
                      <AngleDoubleRight
                        size="1.25rem"
                        style={{ marginRight: '0.5rem', marginTop: '-0.25rem' }}
                      />
                      Start prioritizing
                    </Button>
                  </Link>
                  <Text
                    sx={{
                      textAlign: 'center',
                      fontSize: 1,
                      color: 'grey.7',
                      mt: '0.5rem',
                    }}
                  >
                    {formatNumber(
                      rankedLargefishBarriersDams +
                        rankedLargefishBarriersSmallBarriers
                    )}{' '}
                    available
                  </Text>
                </Box>
              </Flex>

              <Flex sx={{ flexDirection: 'column' }}>
                <Box sx={{ flex: '1 1 auto', mb: '1rem' }}>
                  <Heading as="h4">Small-bodied fish barriers</Heading>
                  <Text sx={{ lineHeight: 1.2 }}>
                    Prioritize dams and road-related barriers based on aquatic
                    networks cut by dams, waterfalls, and road-related barriers
                    with at least minor barrier severity.
                  </Text>
                </Box>
                <Box sx={{ flex: '0 0 auto' }}>
                  <Link to="/priority/smallfish_barriers">
                    <Button sx={{ width: '100%', textAlign: 'left' }}>
                      <AngleDoubleRight
                        size="1.25rem"
                        style={{ marginRight: '0.5rem', marginTop: '-0.25rem' }}
                      />
                      Start prioritizing
                    </Button>
                  </Link>
                  <Text
                    sx={{
                      textAlign: 'center',
                      fontSize: 1,
                      color: 'grey.7',
                      mt: '0.5rem',
                    }}
                  >
                    {formatNumber(
                      rankedSmallfishBarriersDams +
                        rankedSmallfishBarriersSmallBarriers
                    )}{' '}
                    available
                  </Text>
                </Box>
              </Flex>
            </Grid>
          </Box>
        </Grid>
      </Box>
    </Layout>
  )
}
PrioritizePage.propTypes = {
  data: PropTypes.shape({
    headerImage: PropTypes.object.isRequired,
  }).isRequired,
}

export const pageQuery = graphql`
  query PrioritizeStartPageQuery {
    headerImage: file(
      relativePath: { eq: "zack-dutra-2d7Y5Yi3aq8-unsplash.jpg" }
    ) {
      childImageSharp {
        gatsbyImageData(
          layout: FULL_WIDTH
          formats: [AUTO, WEBP]
          placeholder: BLURRED
        )
      }
    }
  }
`

export default PrioritizePage

export const Head = () => (
  <SEO title="Prioritize dams and road-related barriers" />
)

// ui/src/routes/priority/+page.svelte
<script lang="ts">
	import { resolve } from '$app/paths'
	import { SITE_NAME } from '$lib/env'
	import { Button } from '$lib/components/ui/button'
	import { HeaderImage } from '$lib/components/image'

	import { summaryStats } from '$lib/config/summaryStats'

	const {
		rankedDams,
		rankedSmallBarriers,
		rankedLargefishBarriersDams,
		rankedLargefishBarriersSmallBarriers,
		rankedSmallfishBarriersDams,
		rankedSmallfishBarriersSmallBarriers
	} = summaryStats

	const steps = [
		{
			label: 'Select area of interest',
			description:
				'You can select areas using state, county, and watershed boundaries.  Prioritization is limited to areas with dams or assessed barriers depending on the scenario.'
		},
		{
			label: 'Filter barriers',
			description:
				'You can filter barriers by feasibility, height, and other key characteristics to select those that best meet your needs.'
		},
		{
			label: 'Explore priorities on the map',
			description:
				'Once you have defined your area of interest and selected the barriers you want, you can explore them on the map.'
		},
		{
			label: 'Download prioritized barriers',
			description:
				'You can download the inventory for your area of interest and perform offline work.'
		}
	]

	const networkTypes = [
		{
			id: 'dams',
			label: 'Dams',
			description: 'Prioritize dams based on aquatic networks cut by dams and waterfalls.',
			count: rankedDams
		},
		{
			id: 'small_barriers',
			label: 'Surveyed crossings',
			description:
				'Prioritize surveyed road/stream crossings based on aquatic networks cut by dams, waterfalls, and road-related barriers with at least moderate barrier severity.',
			count: rankedSmallBarriers
		},
		{
			id: 'combined_barriers',
			label: 'Dams & surveyed crossings',
			description:
				'Prioritize dams and surveyed road/stream crossings based on aquatic networks cut by dams, waterfalls, and road-related barriers with at least moderate barrier severity.',
			count: rankedDams + rankedSmallBarriers
		},
		{
			id: 'largefish_barriers',
			label: 'Large-bodied fish barriers',
			description:
				'Prioritize dams and surveyed road/stream crossings that are likely to impact large-bodied fish species based on aquatic networks cut by dams and waterfalls that do not have partial or seasonal passability to salmonids and non-salmonids, and road-related barriers with severe or significant barrier severity.',
			count: rankedLargefishBarriersDams + rankedLargefishBarriersSmallBarriers
		},
		{
			id: 'smallfish_barriers',
			label: 'Small-bodied fish barriers',
			description:
				'Prioritize dams and surveyed road/stream crossings based on aquatic networks cut by dams, waterfalls, and road-related barriers with at least minor barrier severity.',
			count: rankedSmallfishBarriersDams + rankedSmallfishBarriersSmallBarriers
		}
	]
</script>

<svelte:head>
	<title>Prioritize dams and surveyed road/stream crossings | {SITE_NAME}</title>
</svelte:head>

<HeaderImage author="Zach Dutra" url="https://unsplash.com/photos/2d7Y5Yi3aq8">
	<enhanced:img src="$lib/assets/images/zack-dutra-2d7Y5Yi3aq8-unsplash.jpg" alt="" />
</HeaderImage>

<div class="grid md:grid-cols-[1fr_2fr] gap-0 pb-8">
	<div class="md:bg-grey-1/75 pt-8 px-4 pb-4">
		<h1 class="text-2xl pb-2 border-b-2 border-b-white">How to prioritize barriers:</h1>

		<div class="mt-4">
			{#each steps as step, i (step.label)}
				<div class="flex gap-2 mt-2 items-center not-first:mt-8">
					<div class="step size-8">{i + 1}</div>
					<div class="text-xl font-bold">{step.label}</div>
				</div>
				<p class="text-sm text-muted-foreground mt-2 ml-10">
					{step.description}
				</p>
			{/each}
		</div>
	</div>

	<div class="mx-8 mt-8 md:mt-0">
		<h2 class="text-2xl mt-8">Prioritization scenarios available:</h2>
		<div class="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mt-4">
			{#each networkTypes as networkType (networkType.id)}
				<div class="bg-blue-1/40 rounded-lg pt-2 px-4 pb-4 border border-grey-2">
					<div class="flex flex-col gap-2 h-full">
						<div class="flex-none font-bold border-b-2 border-b-white pb-2 text-lg">
							{networkType.label}
						</div>
						<div class="flex flex-auto f-full text-sm">
							{networkType.description}
						</div>
						<Button
							href={resolve(`/priority/${networkType.id}/`, { networkType: networkType.id })}
							class="w-full flex-none mt-6">Start prioritizing</Button
						>
					</div>
				</div>
			{/each}
		</div>
	</div>
</div>
