// ui/src/components/BarrierDetails/LocationInfo.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Text } from 'theme-ui'

import {
  barrierTypeLabelSingular,
  OWNERTYPE,
  BARRIEROWNERTYPE,
  FERC_REGULATED,
  STATE_REGULATED,
  WATER_RIGHT,
  STREAM_SIZECLASS,
  STREAM_SIZECLASS_DRAINAGE_AREA,
  WATERBODY_SIZECLASS,
  FISH_HABITAT_PARTNERSHIPS,
  STATES,
  TNC_COLDWATER_STATUS,
  TNC_RESILIENCE,
  TU_BROOK_TROUT_PORTFOLIO,
  WILDSCENIC_RIVER_LONG_LABELS,
} from 'config'
import { OutboundLink } from 'components/Link'
import { Entry, Field } from 'components/Sidebar'
import { formatNumber } from 'util/format'
import { isEmptyString } from 'util/string'
import { BarrierPropType, BarrierDefaultProps } from './proptypes'

const LocationInfo = ({
  annualflow,
  barrierType,
  river,
  huc12,
  basin,
  subwatershed,
  congressionaldistrict,
  ownertype,
  barrierownertype,
  fercregulated,
  stateregulated,
  nrcsdam,
  fedregulatoryagency,
  waterright,
  costlower,
  costmean,
  costupper,
  ejtract,
  ejtribal,
  fishhabitatpartnership,
  nativeterritories,
  intermittent,
  canal,
  storagevolume,
  streamorder,
  streamsizeclass,
  waterbodysizeclass,
  waterbodyacres,
  wilderness,
  wildscenicriver,
  yearsurveyed,
  resurveyed,
  fatality,
  cold,
  resilience,
  brooktroutportfolio,
}) => {
  const barrierTypeLabel = barrierTypeLabelSingular[barrierType]
  const hasRiverName =
    !isEmptyString(river) &&
    river.toLowerCase() !== 'unknown' &&
    river.toLowerCase() !== 'unnamed'

  return (
    <>
      {yearsurveyed !== 0 ? (
        <Entry>
          <Field label="Year surveyed">
            {yearsurveyed}
            {resurveyed !== 0 ? ' (resurveyed)' : null}
          </Field>
        </Entry>
      ) : null}

      <Entry>
        <Text sx={{ fontSize: 1 }}>
          {hasRiverName ? `On ${river} in` : 'Within'} {subwatershed}{' '}
          Subwatershed, {basin} Subbasin{' '}
        </Text>
        <Text sx={{ fontSize: 0, color: 'grey.8' }}>(HUC12: {huc12})</Text>
      </Entry>

      {wildscenicriver ? (
        <>
          <Entry>
            <Text>{WILDSCENIC_RIVER_LONG_LABELS[wildscenicriver]}</Text>
          </Entry>
        </>
      ) : null}

      {wilderness ? (
        <>
          <Entry>
            <Text>Within a designated wilderness area</Text>
          </Entry>
        </>
      ) : null}

      {intermittent === 1 ? (
        <Entry>This {barrierTypeLabel} is on an intermittent reach</Entry>
      ) : null}

      {canal === 1 ? (
        <Entry>This {barrierTypeLabel} is on canal or ditch</Entry>
      ) : null}

      {storagevolume !== null ? (
        <Entry>
          <Field label="Normal storage volume">
            {formatNumber(storagevolume)} acre/feet
          </Field>
        </Entry>
      ) : null}

      {waterbodysizeclass > 0 ? (
        <Entry>
          This {barrierTypeLabel} is associated with a{' '}
          {WATERBODY_SIZECLASS[waterbodysizeclass].split(' (')[0].toLowerCase()}{' '}
          ({formatNumber(waterbodyacres)} acres)
        </Entry>
      ) : null}
      {streamorder > 0 ? (
        <Entry>
          <Field label="Stream order (NHD modified Strahler)">
            {streamorder}
          </Field>
        </Entry>
      ) : null}
      {streamsizeclass ? (
        <Entry>
          <Field label="Stream size class">
            {STREAM_SIZECLASS[streamsizeclass]}
            <br />
            <Text sx={{ fontSize: 0 }}>
              (drainage area: {STREAM_SIZECLASS_DRAINAGE_AREA[streamsizeclass]})
            </Text>
          </Field>
        </Entry>
      ) : null}

      {annualflow !== null && annualflow >= 0 ? (
        <Entry>
          <Field label="Stream reach annual flow rate">
            {formatNumber(annualflow)} CFS
          </Field>
        </Entry>
      ) : null}

      {ownertype !== null && ownertype > 0 ? (
        <Entry>
          <Field label="Conservation land type">{OWNERTYPE[ownertype]}</Field>
        </Entry>
      ) : null}
      {barrierownertype !== null && barrierType !== 'waterfalls' ? (
        <Entry>
          <Field
            label="Barrier ownership type"
            isUnknown={barrierownertype === 0}
          >
            {BARRIEROWNERTYPE[barrierownertype].toLowerCase()}
          </Field>
        </Entry>
      ) : null}

      {fercregulated !== null && fercregulated > 0 ? (
        <Entry>
          <Field
            label="Regulated by the Federal Energy Regulatory Commission"
            isUnknown={fercregulated === 0}
          >
            {FERC_REGULATED[fercregulated].toLowerCase()}
          </Field>
        </Entry>
      ) : null}

      {stateregulated !== null && stateregulated !== -1 ? (
        <Entry>
          <Field
            label="Regulated at the state level"
            isUnknown={stateregulated === 0}
          >
            {STATE_REGULATED[stateregulated].toLowerCase()}
          </Field>
        </Entry>
      ) : null}

      {fedregulatoryagency ? (
        <Entry>
          <Field label="Federal regulatory agency">{fedregulatoryagency}</Field>
        </Entry>
      ) : null}

      {nrcsdam === 1 ? <Entry>This is a NRCS flood control dam</Entry> : null}

      {waterright !== null && waterright > 0 ? (
        <Entry>
          <Field label="Has an associated water right">
            {WATER_RIGHT[waterright].toLowerCase()}
          </Field>
        </Entry>
      ) : null}

      {fatality > 0 ? (
        <Entry>
          <Field label="Number of fatalities recorded">
            {formatNumber(fatality)}
          </Field>
          <Text sx={{ fontSize: 0, color: 'grey.7' }}>
            based on data provided by{' '}
            <OutboundLink to="https://krcproject.groups.et.byu.net/browse.php">
              Fatalities at Submerged Hydraulic Jumps
            </OutboundLink>
          </Text>
        </Entry>
      ) : null}

      {costmean && costmean > 0 ? (
        <Entry>
          <Field label="Estimated cost of removal">
            ${formatNumber(costmean)} (average)
            <br /> (${formatNumber(costlower)} - ${formatNumber(costupper)})
          </Field>
          <Text sx={{ mt: '0.5rem', fontSize: 0, color: 'grey.7' }}>
            Note: costs are modeled based on dam characteristics and are a very
            rough estimate only; please use with caution. Source: Jumani et. al.
            (in prep).
          </Text>
        </Entry>
      ) : null}

      {cold ? (
        <Entry>
          <Field label="Ability of the watershed to maintain cold water habitat">
            {TNC_COLDWATER_STATUS[cold]}
          </Field>
          <Text sx={{ mt: '0.5rem', fontSize: 0, color: 'grey.7' }}>
            based on The Nature Conservancy&apos;s cold water temperature score
            where this barrier occurs (TNC; March 2024).
          </Text>
        </Entry>
      ) : null}

      {resilience ? (
        <Entry>
          <Field label="Freshwater resilience">
            {TNC_RESILIENCE[resilience]}
          </Field>
          <Text sx={{ mt: '0.5rem', fontSize: 0, color: 'grey.7' }}>
            based on the The Nature Conservancy&apos;s freshwater resilience
            category of the watershed where this barrier occurs (v0.44).
          </Text>
        </Entry>
      ) : null}

      {brooktroutportfolio ? (
        <Entry>
          <Field label="Eastern brook trout conservation portfolio">
            {TU_BROOK_TROUT_PORTFOLIO[brooktroutportfolio]}
          </Field>
          <Text sx={{ mt: '0.5rem', fontSize: 0, color: 'grey.7' }}>
            based on the{' '}
            <OutboundLink to="https://www.tu.org/science/conservation-planning-and-assessment/conservation-portfolio/">
              brook trout conservation portfolio
            </OutboundLink>{' '}
            category of the watershed where this barrier occurs, as identified
            by Trout Unlimited (7/4/2022).
          </Text>
        </Entry>
      ) : null}

      {ejtract || ejtribal ? (
        <Entry>
          <Field label="Climate and environmental justice">
            {ejtract ? 'within a disadvantaged census tract' : null}
            {ejtract && ejtribal ? ', ' : null}
            {ejtribal ? 'within a tribal community' : null}
          </Field>
        </Entry>
      ) : null}

      {fishhabitatpartnership ? (
        <Entry>
          <Text>Fish Habitat Partnerships working in this area:</Text>
          <Text sx={{ mt: '0.25rem', ml: '1rem' }}>
            {fishhabitatpartnership.split(',').map((code, i) => (
              <React.Fragment key={code}>
                {i > 0 ? ', ' : null}
                <OutboundLink to={FISH_HABITAT_PARTNERSHIPS[code].url}>
                  {FISH_HABITAT_PARTNERSHIPS[code].name}
                </OutboundLink>
              </React.Fragment>
            ))}
          </Text>
        </Entry>
      ) : null}

      {nativeterritories ? (
        <Entry>
          <Text>Within the following native territories:</Text>
          <Text sx={{ mt: '0.25rem', ml: '1rem' }}>{nativeterritories}</Text>
          <Text sx={{ fontSize: 0, color: 'grey.7', ml: '1rem' }}>
            based on data provided by{' '}
            <OutboundLink to="https://native-land.ca/">
              Native Land Digital
            </OutboundLink>
            .
          </Text>
        </Entry>
      ) : null}

      {congressionaldistrict ? (
        <Entry>
          <Field label="Congressional district">
            {STATES[congressionaldistrict.slice(0, 2)]} Congressional District{' '}
            {congressionaldistrict.slice(2)}
            <Text
              sx={{
                display: 'inline',
                fontSize: 0,
                color: 'grey.7',
                ml: '0.5rem',
              }}
            >
              (118th congress)
            </Text>
          </Field>
        </Entry>
      ) : null}
    </>
  )
}

LocationInfo.propTypes = {
  ...BarrierPropType,
  ownertype: PropTypes.number,
  barrierownertype: PropTypes.number,
  resurveyed: PropTypes.number,
  yearsurveyed: PropTypes.number,

  // dam specific fields
  costlower: PropTypes.number,
  costmean: PropTypes.number,
  costupper: PropTypes.number,
  fatality: PropTypes.number,
  fedregulatoryagency: PropTypes.string,
  fercregulated: PropTypes.number,
  nrcsdam: PropTypes.number,
  stateregulated: PropTypes.number,
  storagevolume: PropTypes.number,
  waterbodyacres: PropTypes.number,
  waterbodysizeclass: PropTypes.number,
  waterright: PropTypes.number,
}

LocationInfo.defaultProps = {
  ...BarrierDefaultProps,
  ownertype: 0,
  barrierownertype: 0,
  resurveyed: 0,
  yearsurveyed: 0,

  // dam specific fields
  costlower: 0,
  costmean: 0,
  costupper: 0,
  fatality: 0,
  fedregulatoryagency: null,
  fercregulated: null,
  nrcsdam: null,
  stateregulated: null,
  storagevolume: null,
  waterbodyacres: null,
  waterbodysizeclass: null,
  waterright: null,
}

export default LocationInfo

// ui/src/lib/components/barrierdetails/LocationInfo.svelte
<script lang="ts">
	import {
		barrierTypeLabelSingular,
		OWNERTYPE,
		BARRIEROWNERTYPE,
		FERC_REGULATED,
		STATE_REGULATED,
		WATER_RIGHT,
		STREAM_SIZECLASS,
		STREAM_SIZECLASS_DRAINAGE_AREA,
		WATERBODY_SIZECLASS,
		FISH_HABITAT_PARTNERSHIPS,
		STATES,
		TNC_COLDWATER_STATUS,
		TNC_RESILIENCE,
		TU_BROOK_TROUT_PORTFOLIO,
		WILDSCENIC_RIVER_LONG_LABELS
	} from '$lib/config/constants'
	import type { BarrierTypePlural } from '$lib/config/types'

	import Entry from './Entry.svelte'
	import { formatNumber } from '$lib/util/format'
	import { isEmptyString } from '$lib/util/string'

	const {
		annualflow = null,
		barrierType,
		river = null,
		huc12,
		basin,
		subwatershed,
		congressionaldistrict = null,
		ownertype = null,
		barrierownertype = null,
		fercregulated = null,
		relicensingyear = null,
		stateregulated = null,
		nrcsdam = null,
		fedregulatoryagency = null,
		waterright = null,
		costlower = null,
		costmean = null,
		costupper = null,
		ejtract = null,
		ejtribal = null,
		fishhabitatpartnership = null,
		nativeterritories = null,
		intermittent = null,
		canal = null,
		storagevolume = null,
		streamorder = null,
		streamsizeclass = null,
		waterbodysizeclass = null,
		waterbodyacres = null,
		wilderness = null,
		wildscenicriver = null,
		yearsurveyed = null,
		resurveyed = null,
		fatality = null,
		cold = null,
		resilience = null,
		brooktroutportfolio = null,
		hasnetwork = false,
		invasivenetwork = null,
		invasive = null
	} = $props()

	const barrierTypeLabel = $derived(barrierTypeLabelSingular[barrierType as BarrierTypePlural])
</script>

{#if yearsurveyed !== null && yearsurveyed !== 0}
	<Entry label="Year surveyed">
		{yearsurveyed}
		{resurveyed !== 0 ? ' (resurveyed)' : null}
	</Entry>
{/if}

<Entry label="Watershed">
	{#if !(isEmptyString(river) && river?.toLowerCase() === 'unknown' && river?.toLowerCase() === 'unnamed')}
		On {river} in
	{:else}
		Within
	{/if}
	{subwatershed} Subwatershed, {basin} Subbasin
	<br />
	<div class="mt-2">
		HUC12: {huc12}
	</div>
</Entry>

{#if wildscenicriver}
	<Entry label="Wild & Scenic River status">
		{WILDSCENIC_RIVER_LONG_LABELS[wildscenicriver as keyof typeof WILDSCENIC_RIVER_LONG_LABELS]}
	</Entry>
{/if}

{#if wilderness}
	<Entry label="Wilderness status">Within a designated wilderness area</Entry>
{/if}

{#if intermittent === 1}
	<Entry label="Stream permanence">
		This {barrierTypeLabel} is on an intermittent reach
	</Entry>
{/if}

{#if canal === 1}
	<Entry label="Canal / ditch position">This {barrierTypeLabel} is on canal or ditch</Entry>
{/if}

{#if storagevolume !== null}
	<Entry label="Normal storage volume">
		{formatNumber(storagevolume)} acre/feet
	</Entry>
{/if}

{#if waterbodysizeclass > 0}
	<Entry label="Related waterbody">
		This {barrierTypeLabel} is associated with a
		{WATERBODY_SIZECLASS[waterbodysizeclass as keyof typeof WATERBODY_SIZECLASS]
			.split(' (')[0]
			.toLowerCase()}
		({formatNumber(waterbodyacres)} acres)
	</Entry>
{/if}

{#if streamorder > 0}
	<Entry label="Stream order (NHD modified Strahler)">
		{streamorder}
	</Entry>
{/if}

{#if streamsizeclass}
	<Entry label="Stream size class">
		{STREAM_SIZECLASS[streamsizeclass as keyof typeof STREAM_SIZECLASS]} ({STREAM_SIZECLASS_DRAINAGE_AREA[
			streamsizeclass as keyof typeof STREAM_SIZECLASS_DRAINAGE_AREA
		]})
	</Entry>
{/if}

{#if annualflow !== null && annualflow >= 0}
	<Entry label="Stream reach annual flow rate">
		{formatNumber(annualflow)} CFS
	</Entry>
{/if}

{#if ownertype > 0}
	<Entry label="Conservation land type">{OWNERTYPE[ownertype as keyof typeof OWNERTYPE]}</Entry>
{/if}

{#if barrierownertype !== null && barrierType !== 'waterfalls'}
	<Entry label="Barrier ownership type" isUnknown={barrierownertype === 0}>
		{BARRIEROWNERTYPE[barrierownertype as keyof typeof BARRIEROWNERTYPE].toLowerCase()}
	</Entry>
{/if}

{#if fercregulated !== null && fercregulated > 0}
	<Entry
		label="Regulated by the Federal Energy Regulatory Commission"
		isUnknown={fercregulated === 0}
	>
		{FERC_REGULATED[fercregulated as keyof typeof FERC_REGULATED]}

		{#if relicensingyear}
			<div class="mt-2">
				License expiration year: {relicensingyear}
			</div>
		{/if}
	</Entry>
{/if}

{#if stateregulated !== null && stateregulated !== -1}
	<Entry label="Regulated at the state level" isUnknown={stateregulated === 0}>
		{STATE_REGULATED[stateregulated as keyof typeof STATE_REGULATED].toLowerCase()}
	</Entry>
{/if}

{#if fedregulatoryagency}
	<Entry label="Federal regulatory agency">{fedregulatoryagency}</Entry>
{/if}

{#if nrcsdam === 1}
	<Entry label="NRCS flood control dam status">This is a NRCS flood control dam</Entry>
{/if}

{#if waterright > 0}
	<Entry label="Has an associated water right">
		{WATER_RIGHT[waterright as keyof typeof WATER_RIGHT].toLowerCase()}
	</Entry>
{/if}

{#if hasnetwork && invasive && invasivenetwork === 1}
	<Entry label="Invasive species management">
		{#if invasive}
			This {barrierTypeLabel} is identified as a beneficial to restricting the movement of invasive species
			and is not ranked for removal or mitigation.
		{:else if invasivenetwork === 1}
			Upstream of a barrier identified as a beneficial to restricting the movement of invasive
			species.
		{/if}
	</Entry>
{/if}

{#if fatality > 0}
	<Entry label="Number of fatalities recorded">
		{formatNumber(fatality)}

		<div class="text-xs text-muted-foreground mt-2">
			Based on data provided by
			<a href="https://krcproject.groups.et.byu.net/browse.php" target="_blank" rel="external">
				Fatalities at Submerged Hydraulic Jumps
			</a>
		</div>
	</Entry>
{/if}

{#if costmean > 0}
	<Entry label="Estimated cost of removal">
		<div class="leading-relaxed">
			average: ${formatNumber(costmean)}
			<br />
			range: ${formatNumber(costlower)} - ${formatNumber(costupper)}
		</div>

		<div class="text-xs text-muted-foreground mt-4">
			Costs are modeled based on dam characteristics (Jumani et. al. in prep) and are a veryrough
			estimate only; please use with caution
		</div>
	</Entry>
{/if}

{#if cold}
	<Entry label="Ability of the watershed to maintain cold water habitat">
		{TNC_COLDWATER_STATUS[cold as keyof typeof TNC_COLDWATER_STATUS]}

		<div class="text-xs text-muted-foreground mt-4">
			Based on The Nature Conservancy's cold water temperature score where this barrier occurs (TNC;
			March 2024).
		</div>
	</Entry>
{/if}

{#if resilience}
	<Entry label="Freshwater resilience">
		{TNC_RESILIENCE[resilience as keyof typeof TNC_RESILIENCE]}
		<div class="text-xs text-muted-foreground mt-4">
			Based on the The Nature Conservancy's freshwater resilience category of the watershed where
			this barrier occurs (v0.44).
		</div>
	</Entry>
{/if}

{#if brooktroutportfolio}
	<Entry label="Eastern brook trout conservation portfolio">
		{TU_BROOK_TROUT_PORTFOLIO[brooktroutportfolio as keyof typeof TU_BROOK_TROUT_PORTFOLIO]}

		<div class="text-xs text-muted-foreground mt-4">
			Based on the
			<a
				href="https://www.tu.org/science/conservation-planning-and-assessment/conservation-portfolio/"
				target="_blank"
				rel="external"
			>
				brook trout conservation portfolio
			</a>
			category of the watershed where this barrier occurs, as identified by Trout Unlimited (7/4/2022).
		</div>
	</Entry>
{/if}

{#if ejtract || ejtribal}
	<Entry label="Climate and environmental justice">
		{ejtract ? 'within a disadvantaged census tract' : null}
		{ejtract && ejtribal ? ', ' : null}
		{ejtribal ? 'within a tribal community' : null}
	</Entry>
{/if}

{#if fishhabitatpartnership}
	<Entry label="Fish Habitat Partnerships working in this area">
		{#each fishhabitatpartnership.split(',') as fhp, i (fhp)}
			{#if i > 0},
			{/if}
			<a
				href={FISH_HABITAT_PARTNERSHIPS[fhp as keyof typeof FISH_HABITAT_PARTNERSHIPS].url}
				target="_blank"
				rel="external"
			>
				{FISH_HABITAT_PARTNERSHIPS[fhp as keyof typeof FISH_HABITAT_PARTNERSHIPS].name}
			</a>
		{/each}
	</Entry>
{/if}

{#if nativeterritories}
	<Entry label="Within the following native territories">
		<div class="ml">
			{nativeterritories}
			<div class="text-xs text-muted-foreground mt-2">
				Based on data provided by
				<a href="https://native-land.ca/" target="_blank" rel="external">Native Land Digital</a>
			</div>
		</div>
	</Entry>
{/if}

{#if congressionaldistrict}
	<Entry label="Congressional district">
		{STATES[congressionaldistrict.slice(0, 2) as keyof typeof STATES]} Congressional District
		{congressionaldistrict.slice(2)}
		<span class="text-xs text-muted-foreground"> (119th congress) </span>
	</Entry>
{/if}
