// ui/src/lib/components/barrierdetails/BarrierDetails.svelte
<script lang="ts">
	import LoadingIcon from '@lucide/svelte/icons/loader-circle'
	import { createQuery } from '@tanstack/svelte-query'

	import { fetchBarrierDetails } from '$lib/api'
	import { CONTACT_EMAIL } from '$lib/env'
	import { Alert } from '$lib/components/alert'
	import { Button } from '$lib/components/ui/button'
	import { METRICS } from '$lib/config/constants'

	import Dam from './Dam.svelte'
	import Footer from './Footer.svelte'
	import Header from './Header.svelte'
	import Scores from './Scores.svelte'
	import SurveyedCrossing from './SurveyedCrossing.svelte'
	import UnsurveyedCrossing from './UnsurveyedCrossing.svelte'
	import Waterfall from './Waterfall.svelte'
	import { cn } from '$lib/utils'

	type Score = { score: number; tier: number }
	type Scores = {
		state?: { [key: string]: Score }
		huc8?: { [key: string]: Score }
		custom?: { [key: string]: Score }
	}

	// IMPORTANT: due to rendering lags, this component appears to render even when
	// data prop is null (should not render due to #if in parent)
	const { data: coreData, onClose } = $props()

	let view: 'details' | 'scores' = $state('details')

	// SARPID is packed for tile data
	const sarpid = $derived(coreData ? coreData.sarpidname.split('|')[0] : null)

	const requestNetworkType = $derived(
		coreData.networkType === 'small_barriers' ? 'combined_barriers' : coreData.networkType
	)
	const dataRequest = createQuery(() => ({
		queryKey: ['barrier-details', requestNetworkType, sarpid],
		queryFn: async () => fetchBarrierDetails(requestNetworkType, sarpid),
		enabled: sarpid !== null
	}))

	const data = $derived({ ...coreData, ...dataRequest.data })

	const hasTabs = $derived(
		data.ranked && (data.barrierType !== 'waterfalls' || data.barrierType === 'road_crossings')
	)

	const scores = $derived.by(() => {
		const tierToPercent = (tier: number) => (100 * (19 - (tier - 1))) / 20

		const out: Scores = {}

		if (
			data.networkType === 'dams' &&
			data.state_ncwc_tier !== null &&
			data.state_ncwc_tier !== undefined &&
			data.state_ncwc_tier !== -1
		) {
			out.state = Object.fromEntries(
				METRICS.map((metric) => {
					const tier = data[`state_${metric}_tier`]
					return [
						metric,
						{
							score: tierToPercent(tier),
							tier
						}
					]
				})
			)
		}

		if (
			data.huc8_ncwc_tier !== null &&
			data.huc8_ncwc_tier !== undefined &&
			data.huc8_ncwc_tier !== -1
		) {
			out.huc8 = Object.fromEntries(
				METRICS.map((metric) => {
					const tier = data[`huc8_${metric}_tier`]
					return [
						metric,
						{
							score: tierToPercent(tier),
							tier
						}
					]
				})
			)
		}

		// add in custom results if available
		if (data.tiers) {
			out.custom = Object.fromEntries(
				METRICS.map((metric) => {
					const tier = data.tiers[metric]
					return [
						metric,
						{
							score: tierToPercent(tier),
							tier
						}
					]
				})
			)
		}

		return out
	})

	$inspect('selectedBarrier', sarpid, data.barrierType, data).with(console.log)
</script>

<!-- data request null indicates 404 type error -->

{#if dataRequest.isSuccess && dataRequest.data}
	<div class="flex flex-col h-full">
		<Header {...data} {onClose} />

		{#if hasTabs}
			<div class="grid grid-cols-2 gap-0 bg-blue-1 flex-none border-t-4 border-t-blue-2">
				<Button
					variant="ghost"
					class={cn('rounded-none', {
						'bg-white font-bold': view === 'details'
					})}
					onclick={() => {
						view = 'details'
					}}
				>
					Overview
				</Button>
				<Button
					variant="ghost"
					class={cn('rounded-none', { 'bg-white font-bold': view === 'scores' })}
					onclick={() => {
						view = 'scores'
					}}>Connectivity ranks</Button
				>
			</div>
		{/if}

		{#if view === 'details'}
			<div
				class={cn('sidebar-barrier-details flex-auto overflow-auto h-full', {
					'pt-4': hasTabs,
					'border-t-2 border-t-blue-8': !hasTabs
				})}
			>
				{#if data.barrierType === 'dams'}
					<Dam {data} />
				{:else if data.barrierType === 'small_barriers'}
					<SurveyedCrossing {data} />
				{:else if data.barrierType === 'road_crossings'}
					<UnsurveyedCrossing {data} />
				{:else if data.barrierType === 'waterfalls'}
					<Waterfall {data} />
				{/if}
			</div>
		{:else}
			<Scores {...data} {scores} />
		{/if}

		<Footer {...data} />
	</div>
{:else if dataRequest.isLoading}
	<div class="container">
		<div class="flex justify-center items-center gap-4 text-xl text-muted-foreground mt-16">
			<LoadingIcon class="size-8 motion-safe:animate-spin" />
			Loading...
		</div>
	</div>
{:else}
	<Alert title="Whoops!">
		There was an error loading these data. Please try clicking on a different barrier or refresh
		this page in your browser.
		<div class="text-sm">
			If it happens again, please
			<a href={`mailto:${CONTACT_EMAIL}`}>contact us</a>.
		</div>
	</Alert>
{/if}

// ui/src/components/BarrierDetails/index.jsx
/* eslint-disable camelcase */
import React from 'react'
import PropTypes from 'prop-types'
import { Envelope, ExclamationTriangle } from '@emotion-icons/fa-solid'
import { Box, Flex, Spinner, Text } from 'theme-ui'
import { useQuery } from 'react-query'

import { fetchBarrierDetails } from 'components/Data/API'
import { Tab, Tabs } from 'components/Tabs'
import {
  siteMetadata,
  barrierTypeLabelSingular,
  barrierNameWhenUnknown,
  RC_PACK_BITS,
} from 'config'
import { isEmptyString } from 'util/string'
import { unpackBits } from 'util/data'

import Header from './Header'
import DamDetails from './DamDetails'
import RoadCrossingDetails from './RoadCrossingDetails'
import SmallBarrierDetails from './SmallBarrierDetails'
import WaterfallDetails from './WaterfallDetails'
import Scores from './Scores'
import { BarrierPropType } from './proptypes'

const { version: dataVersion } = siteMetadata

const tierToPercent = (tier) => (100 * (19 - (tier - 1))) / 20

const BarrierDetails = ({ barrier, onClose }) => {
  const {
    lat,
    lon,
    barrierType,
    networkType,
    sarpidname = '|', // should never be empty, but breaks badly if it is
    ranked,
    packed,
    tiers = null,
  } = barrier

  const typeLabel = barrierTypeLabelSingular[barrierType]
  const [sarpid, rawName] = sarpidname.split('|')
  const name = !isEmptyString(rawName)
    ? rawName
    : barrierNameWhenUnknown[barrierType] || 'Unknown name'

  console.log('show barrier details: ', sarpid, barrier)

  const { isLoading, error, data } = useQuery(
    ['getBarrierDetails', sarpid],
    () => fetchBarrierDetails(networkType, sarpid),
    {
      // FIXME:
      // staleTime: 60 * 60 * 1000, // 60 minutes
      staleTime: 1, // use then reload to force refresh of underlying data during dev
      refetchOnWindowFocus: false,
      refetchOnMount: false,
    }
  )

  let content = null

  if (isLoading || true) {
    content = (
      <Flex
        sx={{
          alignItems: 'center',
          flexDirection: 'column',
          p: '1rem',
          mt: '2rem',
          flex: '1 1 auto',
        }}
      >
        <Flex sx={{ alignItems: 'center', gap: '0.5rem' }}>
          <Spinner size="2rem" />
          <Text>Loading details...</Text>
        </Flex>
      </Flex>
    )
  }

  if (error) {
    content = (
      <Flex
        sx={{
          alignItems: 'center',
          flexDirection: 'column',
          p: '1rem',
          mt: '2rem',
          flex: '1 1 auto',
        }}
      >
        <Flex sx={{ color: 'highlight', alignItems: 'center' }}>
          <ExclamationTriangle size="2em" />
          <Text sx={{ ml: '0.5rem', fontSize: '2rem' }}>Whoops!</Text>
        </Flex>
        There was an error loading these data. Please try clicking on a
        different barrier or refresh this page in your browser.
        <Text variant="help" sx={{ mt: '2rem' }}>
          If it happens again, please{' '}
          <a href="mailto:kat@southeastaquatics.net">contact us</a>.
        </Text>
      </Flex>
    )
  }

  let county = ''
  let state = ''
  if (data) {
    console.log('barrier details:', sarpid, data)

    county = data.county
    state = data.state

    let details = null
    let packedInfo = null
    switch (barrierType) {
      case 'dams': {
        details = (
          <DamDetails
            barrierType={barrierType}
            networkType={networkType}
            sarpid={sarpid}
            {...data}
          />
        )
        break
      }
      case 'small_barriers': {
        details = (
          <SmallBarrierDetails
            barrierType={barrierType}
            networkType={networkType}
            sarpid={sarpid}
            {...data}
          />
        )
        break
      }
      case 'road_crossings': {
        // FIXME: remove
        packedInfo = unpackBits(packed, RC_PACK_BITS)
        // parse EJTract, EJTribal back to DisadvantagedCommunity
        const disadvantagedcommunityParts = []
        if (packedInfo.ejtract) {
          disadvantagedcommunityParts.push('tract')
        }
        if (packedInfo.ejtribal) {
          disadvantagedcommunityParts.push('tribal')
        }
        const disadvantagedcommunity = disadvantagedcommunityParts.join(',')

        details = (
          <RoadCrossingDetails
            sarpid={sarpid}
            {...data}
            {...packedInfo}
            disadvantagedcommunity={disadvantagedcommunity}
          />
        )
        break
      }
      case 'waterfalls': {
        details = <WaterfallDetails sarpid={sarpid} {...data} />
        break
      }
      default: {
        // no-op
        break
      }
    }

    let scoreContent = null
    if (ranked) {
      // Transform properties to priorities: <unit>_<metric>_score
      // For now, we are using tier to save space in data transport, so convert them to percent
      const scores = {}
      const metrics = ['nc', 'wc', 'ncwc', 'pnc', 'pwc', 'pncwc']

      // state ranks are only available for dams networks (not combined)
      if (
        networkType === 'dams' &&
        data.state_ncwc_tier !== null &&
        data.state_ncwc_tier !== undefined &&
        data.state_ncwc_tier !== -1
      ) {
        scores.state = {}
        metrics.forEach((metric) => {
          const tier = data[`state_${metric}_tier`]
          scores.state[metric] = {
            score: tierToPercent(tier),
            tier,
          }
        })
      }

      // add in custom results if available
      if (tiers) {
        scores.custom = {}
        metrics.forEach((metric) => {
          const tier = tiers[metric]
          scores.custom[metric] = {
            score: tierToPercent(tier),
            tier,
          }
        })
      }

      scoreContent = <Scores scores={scores} networkType={networkType} />
    }

    if (ranked) {
      content = (
        <Tabs
          sx={{
            flex: '1 1 auto',
            overflow: 'hidden',
          }}
        >
          <Tab id="details" label="Overview">
            {details}
          </Tab>
          <Tab id="ranks" label="Connectivity Ranks">
            {scoreContent}
          </Tab>
        </Tabs>
      )
    } else {
      // Only show details, not scores if cannot be ranked
      content = (
        <Box
          sx={{
            flex: '1 1 auto',
            px: '0.5rem',
            pb: '1rem',
            overflowY: 'auto',
            overflowX: 'hidden',
          }}
        >
          {details}
        </Box>
      )
    }
  }

  return (
    <>
      <Header
        barrierType={barrierType}
        networkType={networkType}
        sarpid={sarpid}
        name={name}
        lat={lat}
        lon={lon}
        county={county}
        state={state}
        onClose={onClose}
      />

      {content}

      <Flex
        sx={{
          flex: '0 0 auto',
          justifyContent: 'center',
          alignItems: 'center',
          py: '0.5rem',
          borderTop: '1px solid #DDD',
          bg: '#f6f6f2',
        }}
      >
        <a
          href={`mailto:Kat@southeastaquatics.net?subject=Problem with SARP Inventory for ${typeLabel}: ${sarpid} (data version: ${dataVersion})&body=I found the following problem with the SARP Inventory for this barrier:`}
        >
          <Envelope size="1rem" style={{ marginRight: '0.25rem' }} /> Report a
          problem with this barrier
        </a>
      </Flex>
    </>
  )
}

BarrierDetails.propTypes = {
  barrier: BarrierPropType.isRequired,
  onClose: PropTypes.func.isRequired,
}

export default BarrierDetails
