// ui/src/components/Map/Legend/index.jsx
import React, { useState } from 'react'
import PropTypes from 'prop-types'
import { Box, Flex, Text } from 'theme-ui'
import { CaretDown } from '@emotion-icons/fa-solid'

import Circle from './Circle'

const Legend = ({
  title,
  subtitle,
  patches,
  circles,
  lines,
  footnote,
  maxWidth,
}) => {
  const [isOpen, setIsOpen] = useState(false)

  const hasElements =
    (patches && patches.length > 0) ||
    (circles && circles.length > 0) ||
    (lines && lines.length > 0)

  if (!(hasElements || footnote)) {
    return null
  }

  const toggleOpen = () => {
    setIsOpen((prevIsOpen) => !prevIsOpen)
  }

  return (
    <Box
      title={isOpen ? 'Click to hide legend' : 'Show legend'}
      onClick={toggleOpen}
      sx={{
        position: 'absolute',
        zIndex: 1000,
        right: '10px',
        bottom: '24px',
        maxWidth,
        py: '0.5em',
        px: '0.75em',
        bg: '#FFF',
        cursor: 'pointer',
        border: '1px solid #AAA',
        borderRadius: '4px',
        boxShadow: '1px 1px 8px #333',
      }}
    >
      {isOpen ? (
        <>
          <Flex
            sx={{
              alignItems: 'center',
              mb: '0.25em',
              fontSize: 2,
              fontWeight: 'bold',
            }}
          >
            {hasElements ? (
              <Box sx={{ mr: '0.25rem' }}>
                <CaretDown size="1.5em" />
              </Box>
            ) : null}

            <Text>{title}</Text>
          </Flex>

          {subtitle ? (
            <Box
              sx={{
                fontSize: 0,
                color: 'grey.7',
                lineHeight: 1.2,
                mb: '0.5rem',
              }}
            >
              {subtitle}
            </Box>
          ) : null}

          {patches && patches.length > 0 ? (
            <div>
              {patches.map(({ id, label, entries }) => (
                <Box
                  key={id}
                  sx={{
                    '&:not(:first-of-type)': {
                      mt: '0.25rem',
                      pt: '0.25rem',
                    },
                  }}
                >
                  {label ? (
                    <Text
                      sx={{
                        my: '0.5rem',
                        fontWeight: 'bold',
                        fontSize: 'small',
                        lineHeight: 1.2,
                      }}
                    >
                      {label}
                    </Text>
                  ) : null}
                  <div>
                    {entries.map(({ color, label: patchLabel }) => (
                      <Flex
                        key={`${patchLabel}-${color}`}
                        sx={{
                          '&:first-of-type > div': {
                            borderTopLeftRadius: '3px',
                            borderTopRightRadius: '3px',
                            borderTopWidth: '1px',
                          },
                          '&:last-of-type > div': {
                            borderBottomLeftRadius: '3px',
                            borderBottomRightRadius: '3px',
                          },
                        }}
                      >
                        <Box
                          sx={{
                            width: '20px',
                            height: '1em',
                            flex: '0 0 auto',
                            borderWidth: '0 1px 1px 1px',
                            borderStyle: 'solid',
                            borderColor: 'grey.5',
                            bg: color,
                          }}
                        />
                        <Text
                          sx={{
                            fontSize: '0.75rem',
                            ml: '0.5rem',
                            lineHeight: 1,
                            color: 'grey.7',
                          }}
                        >
                          {patchLabel}
                        </Text>
                      </Flex>
                    ))}
                  </div>
                </Box>
              ))}
            </div>
          ) : null}

          {patches && patches.length > 0 && circles && circles.length > 0 ? (
            <Box
              sx={{
                mt: '0.5rem',
                borderTop: '1px solid',
                borderTopColor: 'grey.1',
              }}
            />
          ) : null}

          {circles && circles.length > 0 ? (
            <div>
              {circles.map((point) => (
                <Flex
                  key={point.label}
                  sx={{
                    alignItems: 'flex-start',
                    py: '0.25em',
                    '&:not(:first-of-type)': {
                      borderTop: '1px solid',
                      borderTopColor: 'grey.1',
                    },
                  }}
                >
                  <Flex
                    sx={{
                      flex: '0 0 auto',
                      alignItems: 'baseline',
                      width: '12px',
                      mr: '0.5rem',
                    }}
                  >
                    {point.symbols ? (
                      point.symbols.map((p, i) => (
                        <Circle
                          /* eslint-disable-next-line react/no-array-index-key */
                          key={`${p.color}-${p.borderColor}-${i}`}
                          {...p}
                        />
                      ))
                    ) : (
                      <Circle {...point} />
                    )}
                  </Flex>
                  <Text
                    sx={{
                      fontSize: '0.75rem',
                      ml: '0.5rem',
                      lineHeight: 1,
                      color: 'grey.7',
                    }}
                  >
                    {point.label}
                  </Text>
                </Flex>
              ))}
            </div>
          ) : null}

          {((patches && patches.length > 0) ||
            (circles && circles.length > 0)) &&
          lines &&
          lines.length > 0 ? (
            <Box
              sx={{
                mt: '0.5rem',
                borderTop: '1px solid',
                borderTopColor: 'grey.1',
              }}
            />
          ) : null}

          {lines && lines.length > 0 ? (
            <div>
              {lines.map(
                ({
                  id,
                  label: lineLabel,
                  color,
                  lineWidth = '1px',
                  lineStyle = 'solid',
                }) => (
                  <Flex
                    key={id}
                    sx={{
                      alignItems: 'flex-start',
                      py: '0.25em',
                      '&:not(:first-of-type)': {
                        borderTop: '1px solid',
                        borderTopColor: 'grey.1',
                      },
                    }}
                  >
                    <Box
                      sx={{
                        flex: '0 0 auto',
                        width: '1.1rem',
                        height: '0.5rem',
                        borderBottomWidth: lineWidth,
                        borderBottomColor: color,
                        borderBottomStyle: lineStyle,
                      }}
                    />
                    <Text
                      sx={{
                        fontSize: '0.75rem',
                        ml: '0.5rem',
                        lineHeight: 1,
                        color: 'grey.7',
                      }}
                    >
                      {lineLabel}
                    </Text>
                  </Flex>
                )
              )}
            </div>
          ) : null}

          {footnote ? (
            <Text
              variant="help"
              sx={{
                mt: '0.5rem',
                pt: '0.5rem',
                lineHeight: 1.2,
                borderTop: '1px solid',
                borderTopColor: 'grey.1',
                fontSize: 0,
              }}
            >
              {footnote}
            </Text>
          ) : null}
        </>
      ) : (
        <Text
          sx={{ fontSize: 1, fontWeight: 'bold' }}
          title="click to open legend"
        >
          Legend
        </Text>
      )}
    </Box>
  )
}

Legend.propTypes = {
  title: PropTypes.string,
  subtitle: PropTypes.string,
  circles: PropTypes.arrayOf(
    PropTypes.shape({
      color: PropTypes.string,
      label: PropTypes.string,
      radius: PropTypes.number,
      borderWidth: PropTypes.number,
      borderColor: PropTypes.string,
      symbols: PropTypes.arrayOf(
        PropTypes.shape({
          color: PropTypes.string.isRequired,
          radius: PropTypes.number.isRequired,
          borderWidth: PropTypes.number,
          borderColor: PropTypes.string,
        })
      ),
    })
  ),
  patches: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.string.isRequired,
      label: PropTypes.string,
      entries: PropTypes.arrayOf(
        PropTypes.shape({
          color: PropTypes.string.isRequired,
          label: PropTypes.string.isRequired,
        }).isRequired
      ),
    })
  ),
  lines: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.string.isRequired,
      label: PropTypes.string.isRequired,
      color: PropTypes.string.isRequired,
      lineWidth: PropTypes.string,
      lineStyle: PropTypes.string,
    })
  ),
  footnote: PropTypes.string,
  maxWidth: PropTypes.string,
}

Legend.defaultProps = {
  title: 'Legend',
  subtitle: null,
  circles: null,
  patches: null,
  lines: null,
  footnote: null,
  maxWidth: '16rem',
}

export default Legend

// ui/src/lib/components/map/legend/Legend.svelte
<script lang="ts">
	import CloseIcon from '@lucide/svelte/icons/chevron-down'
	import { Button } from '$lib/components/ui/button'

	import Circle from './Circle.svelte'

	const {
		title = 'Legend',
		subtitle = null,
		patches = [],
		circles = [],
		lines = [],
		footnote = null
	} = $props()

	const hasElements = $derived(
		(patches && patches.length > 0) ||
			(circles && circles.length > 0) ||
			(lines && lines.length > 0)
	)

	let isOpen = $state(false)
</script>

{#if hasElements || footnote}
	{#if isOpen}
		<div
			class="absolute right-2.5 bottom-6 text-sm px-4 pt-1 pb-2 bg-white hover:bg-white text-foreground border border-grey-5 rounded-md shadow-grey-6 shadow-lg max-w-[16rem]"
		>
			<Button
				variant="ghost"
				class="block w-full h-auto p-0! font-bold"
				onclick={() => {
					isOpen = false
				}}
			>
				<div class="flex items-center gap-2 justify-between text-lg">
					{title}
					<CloseIcon class="size-5" />
				</div>
			</Button>
			{#if subtitle}
				<div class="text-xs text-muted-foreground leading-tight mb-2">
					{subtitle}
				</div>
			{/if}

			{#if patches && patches.length > 0}
				<div>
					{#each patches as patch (patch.id)}
						<div class="not-first-of-type:mt-2">
							{#if patch.label}
								<div class="mb-1 font-bold leading-tight text-sm">
									{patch.label}
								</div>
							{/if}

							<div>
								{#each patch.entries as entry (`${entry.label}-${entry.color}`)}
									<div class="flex gap-2 group">
										<div
											class="ml-1 h-4 w-5 flex-none border-grey-5 border-t-none border-l border-r border-b group-first-of-type:rounded-t-sm group-last-of-type:rounded-b-sm group-first-of-type:border-t"
											style="background-color:{entry.color}"
										></div>
										<div class="text-xs leading-none text-foreground">{entry.label}</div>
									</div>
								{/each}
							</div>
						</div>
					{/each}
				</div>
			{/if}

			{#if circles && circles.length > 0}
				{#if patches && patches.length > 0}
					<hr class="mt-2 mb-0 border-grey-1" />
				{/if}

				<div>
					{#each circles as circle (circle.id)}
						<div
							class="flex items-start pt-2 not-first:border-t not-first:border-t-grey-1 not-first:mt-1 gap-2"
						>
							<div class="flex flex-none items-baseline min-w-5">
								{#if circle.symbols && circle.symbols.length > 0}
									{#each circle.symbols as symbol, i (`${symbol.color}-${symbol.borderColor}-${i}`)}
										<Circle {...symbol} />
									{/each}
								{:else}
									<Circle {...circle} />
								{/if}
							</div>
							<div class="text-xs leading-none text-foreground">{circle.label}</div>
						</div>
					{/each}
				</div>
			{/if}

			{#if lines && lines.length > 0}
				{#if (patches && patches.length > 0) || (circles && circles.length > 0)}
					<hr class="mt-2 mb-0 border-grey-1" />
				{/if}

				<div>
					{#each lines as line (line.id)}
						<div
							class="flex items-start pt-2 not-first:border-t not-first:border-t-grey-1 not-first:mt-1 gap-2"
						>
							<div
								class="flex-none w-5 h-2"
								style="border-bottom-color:{line.color}; border-bottom-width:{line.lineWidth * 2 ||
									2}px; border-bottom-style:{line.lineStyle || 'solid'};"
							></div>
							<div class="text-xs leading-none text-foreground">{line.label}</div>
						</div>
					{/each}
				</div>
			{/if}

			{#if footnote}
				<div class="text-xs text-muted-foreground mt-2 pt-2 leading-tight border-t border-t-grey-1">
					{footnote}
				</div>
			{/if}
		</div>
	{:else}
		<Button
			onclick={() => {
				isOpen = true
			}}
			title="Click to show legend"
			class="absolute right-2.5 bottom-6 text-sm py-2 bg-white hover:bg-white text-foreground border-none font-bold"
			style="box-shadow:0 0 0 2px #0000001a"
		>
			Legend
		</Button>
	{/if}
{/if}
