// ui/src/lib/components/explore/UnitListItem.svelte
<script lang="ts">
	import CloseIcon from '@lucide/svelte/icons/circle-x'
	import { resolve } from '$app/paths'

	import { Button } from '$lib/components/ui/button'
	import { STATE_FIPS, STATES } from '$lib/config/constants'
	import { formatNumber, pluralize } from '$lib/util/format'
	import { cn } from '$lib/utils'

	const { barrierType, system, unit, ignore, onDelete, onZoomBounds } = $props()

	const {
		id,
		layer,
		bbox = null,
		dams = 0,
		totalSmallBarriers = 0,
		unsurveyedRoadCrossings = 0
	} = $derived(unit)

	const name = $derived(layer === 'State' ? STATES[id as keyof typeof STATES] : unit.name)

	const { count, countMessage } = $derived.by(() => {
		const totalRoadBarriers = totalSmallBarriers + unsurveyedRoadCrossings

		switch (barrierType) {
			case 'dams': {
				return {
					count: dams,
					countMessage: `${formatNumber(dams)} ${pluralize('dam', dams)}`
				}
			}
			case 'small_barriers': {
				return {
					count: totalSmallBarriers,
					countMessage: `${formatNumber(totalSmallBarriers)} surveyed road/stream ${pluralize(
						'crossing',
						totalSmallBarriers
					)} (out of ${formatNumber(totalRoadBarriers)} total ${pluralize(
						'crossing',
						totalRoadBarriers
					)})`
				}
			}
			case 'combined_barriers': {
				return {
					count: dams + totalSmallBarriers,
					countMessage: `${formatNumber(dams)} ${pluralize('dam', dams)} and ${formatNumber(
						totalSmallBarriers
					)} surveyed road/stream ${pluralize(
						'crossing',
						totalSmallBarriers
					)} (out of ${formatNumber(totalRoadBarriers)} total ${pluralize(
						'crossing',
						totalRoadBarriers
					)})`
				}
			}
		}
	}) as { count: number; countMessage: string }
</script>

<li
	class="grid grid-cols-[3.5fr_1fr] gap-4 py-2 not-first-of-type:border-t not-first-of-type:border-t-grey-1 mt-2"
>
	<div>
		<div
			class={cn('text-sm', {
				'font-bold': count > 0 && !ignore,
				'italic text-muted-foreground': count === 0 || ignore
			})}
		>
			{name}{layer === 'County' ? ', ' : ''}

			{#if layer === 'State'}
				<span class="font-normal text-xs text-muted-foreground">
					(<a href={resolve(`/states/${id}`, { id })}>view state details</a>)</span
				>
			{:else if layer === 'County'}
				{STATE_FIPS[id.slice(0, 2) as keyof typeof STATE_FIPS]}
			{/if}
		</div>

		{#if system === 'HUC'}
			<div class={cn('text-xs', { 'italic text-muted-foreground': count === 0 })}>
				{layer}: {id}
			</div>
		{/if}

		<div class="text-xs text-muted-foreground">
			{countMessage}
			{#if ignore}
				(already counted in larger selected area)
			{/if}
		</div>
	</div>

	<div class="flex flex-col justify-between items-end h-full">
		<Button
			variant="ghost"
			onclick={() => onDelete(unit)}
			class="p-0! h-auto flex-none text-muted-foreground hover:text-foreground"
			aria-label={`remove ${name} from list`}
		>
			<CloseIcon class="size-5" />
		</Button>

		{#if bbox}
			<Button
				variant="link"
				onclick={() => onZoomBounds(bbox)}
				class="p-0! text-xs h-auto mt-1"
				aria-label={`zoom to ${name} on the map`}
			>
				zoom to
			</Button>
		{/if}
	</div>
</li>

// ui/src/components/Explore/UnitListItem.jsx
import React, { memo } from 'react'
import PropTypes from 'prop-types'
import { Box, Flex, Grid, Button, Text } from 'theme-ui'

import { STATE_FIPS, STATES } from 'config'
import { OutboundLink } from 'components/Link'
import { formatNumber, pluralize } from 'util/format'

const UnitListItem = ({
  barrierType,
  system,
  unit,
  ignore,
  onDelete,
  onZoomBounds,
}) => {
  const {
    id,
    layer,
    bbox = null,
    dams = 0,
    totalSmallBarriers = 0,
    unsurveyedRoadCrossings = 0,
  } = unit
  let { name = id } = unit

  if (layer === 'State') {
    name = STATES[id]
  }

  let count = 0
  let countMessage = null

  const totalRoadBarriers = totalSmallBarriers + unsurveyedRoadCrossings

  switch (barrierType) {
    case 'dams': {
      count = dams
      countMessage = `${formatNumber(dams)} ${pluralize('dam', dams)}`

      break
    }
    case 'small_barriers': {
      count = totalSmallBarriers

      countMessage = `${formatNumber(
        totalSmallBarriers
      )} assessed road/stream ${pluralize(
        'crossing',
        totalSmallBarriers
      )} (out of ${formatNumber(totalRoadBarriers)} total ${pluralize(
        'crossing',
        totalRoadBarriers
      )})`

      break
    }
    case 'combined_barriers': {
      count = dams + totalSmallBarriers

      countMessage = `${formatNumber(dams)} ${pluralize(
        'dam',
        dams
      )} and ${formatNumber(
        totalSmallBarriers
      )} assessed road/stream ${pluralize(
        'crossing',
        totalSmallBarriers
      )} (out of ${formatNumber(totalRoadBarriers)} total ${pluralize(
        'crossing',
        totalRoadBarriers
      )})`

      break
    }
    default: {
      break
    }
  }

  const handleDelete = () => onDelete(unit)

  const handleZoomBounds = () => onZoomBounds(bbox)

  return (
    <Grid
      as="li"
      columns="1fr 3.5rem"
      gap={1}
      sx={{
        mx: '-1rem',
        px: '1rem',
        py: '0.5em',
        '&:not(:first-of-type)': {
          borderTop: '1px solid',
          borderTopColor: 'grey.1',
        },
        '&:last-of-type': {
          borderBottom: '1px solid',
          borderBottomColor: 'grey.1',
        },
      }}
    >
      <Box
        sx={{
          flex: '1 1 auto',
          mr: '1em',
        }}
      >
        <Text
          sx={{
            fontSize: 1,
            fontWeight: count > 0 && !ignore ? 'bold' : 'inherit',
            fontStyle: count === 0 || ignore ? 'italic' : 'inherit',
            color: count === 0 || ignore ? 'grey.8' : 'inherit',
          }}
        >
          {name}

          {layer === 'State' ? (
            <Text
              sx={{
                display: 'inline',
                fontWeight: 'normal',
                fontSize: 0,
                color: 'grey.7',
              }}
            >
              {' '}
              (
              <OutboundLink to={`/states/${id}`}>
                view state details
              </OutboundLink>
              )
            </Text>
          ) : null}

          {layer === 'County' ? `, ${STATE_FIPS[id.slice(0, 2)]}` : null}
        </Text>

        {system === 'HUC' ? (
          <Text
            sx={{
              fontSize: 0,
              fontStyle: count === 0 ? 'italic' : 'inherit',
              color: count === 0 ? 'grey.8' : 'inherit',
            }}
          >
            {layer}: {id}
          </Text>
        ) : null}

        {countMessage !== null ? (
          <Text variant="help" sx={{ fontSize: 0 }}>
            {countMessage}
            {ignore ? ' (already counted in larger selected area)' : null}
          </Text>
        ) : null}
      </Box>

      <Flex
        sx={{
          flex: '0 0 auto',
          flexDirection: 'column',
          justifyContent: 'space-between',
          alignItems: 'flex-end',
          height: '100%',
        }}
      >
        <Box sx={{ flex: '1 1 auto' }}>
          <Button variant="close" onClick={handleDelete}>
            &#10006;
          </Button>
        </Box>
        {bbox ? (
          <Box
            onClick={handleZoomBounds}
            sx={{
              flex: '0 0 auto',
              fontSize: 0,
              color: 'link',
              cursor: 'pointer',
              textDecoration: 'none',
              '&:hover': { textDecoration: 'underline' },
            }}
          >
            zoom to
          </Box>
        ) : null}
      </Flex>
    </Grid>
  )
}

UnitListItem.propTypes = {
  barrierType: PropTypes.string.isRequired,
  system: PropTypes.string.isRequired,
  unit: PropTypes.object.isRequired,
  ignore: PropTypes.bool,
  onDelete: PropTypes.func.isRequired,
  onZoomBounds: PropTypes.func.isRequired,
}

UnitListItem.defaultProps = {
  ignore: false,
}

export default memo(UnitListItem)
