// ui/src/lib/components/layout/Footer.svelte
<script lang="ts">
	import { NACC_HOME_URL } from '#lib/env.js'
	import { dataVersion, dataDate } from '#lib/config/constants.js'
	import { resolve } from '$app/paths'
</script>

<footer
	class="flex-none leading-none bg-blue-9 lg:flex items-center justify-between px-2 py-1 text-[0.8rem] gap-6 [&_a]:text-white [&_a]:no-underline [&_a]:hover:underline print:hidden"
>
	<div class="flex-none flex gap-2 [&>a+a]:border-l [&>a+a]:border-grey-4 [&>a+a]:pl-2 [&_a]:block">
		<a href={NACC_HOME_URL} class="block text-white no-underline hover:underline">NACC Home</a>
		<a href="https://southeastaquatics.net/sarps-programs/aquatic-connectivity-program-act"
			>Southeast Aquatic Resources Partnership</a
		>
		<a href="https://southeastaquatics.net/about/contact-us">Contact Us </a>
		<a href={resolve('/terms-of-use/', {})}> Terms of Use</a>
	</div>
	<div class="flex-auto text-white text-center hidden md:block">
		Data version: {dataVersion} ({dataDate})
	</div>
	<div class="flex-none text-white hidden lg:block">
		Created by
		<a href="https://astutespruce.com">Astute Spruce, LLC</a>
	</div>
</footer>

// ui/src/components/Layout/Footer.jsx
import React from 'react'

import { Box, Flex } from 'theme-ui'
import { OutboundLink, Link } from 'components/Link'

import { siteMetadata } from 'config'

const { version: dataVersion, date: dataDate } = siteMetadata

const Footer = () => (
  <Flex
    as="footer"
    sx={{
      flex: '0 0 auto',
      alignItems: 'center',
      justifyContent: 'space-between',
      py: '0.25rem',
      px: '0.5rem',
      color: '#FFF',
      bg: 'blue.9',
      fontSize: '0.8rem',
      a: {
        textDecoration: 'none',
        color: '#FFF',
      },
    }}
  >
    <Box>
      <OutboundLink to="https://southeastaquatics.net/sarps-programs/aquatic-connectivity-program-act">
        Southeast Aquatic Resources Partnership
      </OutboundLink>
      &nbsp;&nbsp;|&nbsp;&nbsp;
      <OutboundLink to="https://southeastaquatics.net/about/contact-us">
        Contact Us
      </OutboundLink>
      &nbsp;&nbsp;|&nbsp;&nbsp;
      <Link to="/terms">Terms of Use</Link>
    </Box>

    <Box>
      Data version: {dataVersion} ({dataDate})
    </Box>

    <Box>
      Created by{' '}
      <OutboundLink to="https://astutespruce.com">
        Astute Spruce, LLC
      </OutboundLink>
    </Box>
  </Flex>
)

export default Footer
