// ui/src/routes/fhp/+page.svelte
<script lang="ts">
	import { resolve } from '$app/paths'
	import { HeaderImage } from '$lib/components/image'
	import { SITE_NAME } from '$lib/env'
	import { FISH_HABITAT_PARTNERSHIPS } from '$lib/config/constants'

	import NFHPLogo from '$lib/assets/images/nfhp_logo.svg'

	const mapImages = import.meta.glob('$lib/assets/images/maps/fhp/*.png', {
		eager: true,
		import: 'default',
		query: {
			w: '500;250',
			format: 'avif;webp;png',
			as: 'picture'
		}
	})

	const maps: { [key: string]: any } = {}
	for (const path in mapImages) {
		const [region] = path.split('/').slice(-1)[0].split('.')
		maps[region] = mapImages[path]
	}

	const fhps = Object.entries(FISH_HABITAT_PARTNERSHIPS)
		.sort(([leftId], [rightId]) => (leftId <= rightId ? -1 : 1))
		.map(([id, { name }]) => ({ id, name }))
</script>

<svelte:head>
	<title>Fish Habitat Partnerships | {SITE_NAME}</title>
</svelte:head>

<HeaderImage
	author="Brook trout. Photo: Jason Ross/USFWS."
	url="https://www.flickr.com/photos/usfwsmidwest/34597621345/"
>
	<enhanced:img src="$lib/assets/images/34597621345_26d60382fd_o.jpg" alt="" />
</HeaderImage>

<div class="page-content">
	<h1>Fish Habitat Partnerships</h1>

	<div class="grid sm:grid-cols-[2fr_1fr] gap-8 mt-12">
		<p>
			The
			<a href="https://www.fishhabitat.org/" target="_blank" rel="external">
				National Fish Habitat Partnership
			</a>
			works to conserve and protect the nation&apos;s fisheries and aquatic systems through a network
			of 20 Fish Habitat Partnerships.
		</p>
		<figure>
			<img src={NFHPLogo} alt="National Fish Habitat Partnership logo" class="w-[264px] h-[56px]" />
		</figure>
	</div>

	<div class="font-bold text-xl mt-12">
		View more about the status of the inventory in each Fish Habitat Partnership:
	</div>

	<div class="grid sm:grid-cols-3 gap-6 bg-blue-0 p-4 items-stretch mt-2">
		{#each fhps as fhp (fhp.id)}
			<a
				href={resolve(`/fhp/${fhp.id}/`)}
				class="bg-white p-2 border border-grey-1 rounded-sm h-full flex flex-col justify-end hover:shadow-md hover:border-grey-8 no-underline"
			>
				<div>
					{fhp.name}
				</div>

				<enhanced:img
					src={maps[fhp.id]}
					alt={`${fhp.name} map`}
					class="border border-grey-4 mt-1"
				/>
			</a>
		{/each}
	</div>
</div>

// ui/src/pages/fhp/index.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { graphql } from 'gatsby'
import { Box, Container, Flex, Grid, Heading, Image, Paragraph } from 'theme-ui'

import { FISH_HABITAT_PARTNERSHIPS } from 'config'
import { Link, OutboundLink } from 'components/Link'
import { Layout, SEO } from 'components/Layout'
import { HeaderImage } from 'components/Image'
import { dynamicallyLoadImage } from 'util/dom'
import NFHPLogo from 'images/nfhp_logo.svg'

const FHPListPage = ({ data: { headerImage } }) => (
  <Layout>
    <HeaderImage
      image={headerImage.childImageSharp.gatsbyImageData}
      height="20vh"
      minHeight="18rem"
      credits={{
        author: 'Brook trout,  Jason Ross/USFWS',
        url: 'https://www.flickr.com/photos/usfwsmidwest/34597621345/',
      }}
    />

    <Container>
      <Heading as="h1">Fish Habitat Partnerships</Heading>
      <Grid columns="2fr 1fr" gap={5} sx={{ mt: '1rem' }}>
        <Paragraph variant="paragraph.large">
          The{' '}
          <OutboundLink to="https://www.fishhabitat.org/">
            {' '}
            National Fish Habitat Partnership
          </OutboundLink>{' '}
          works to conserve and protect the nation&apos;s fisheries and aquatic
          systems through a network of 20 Fish Habitat Partnerships.
        </Paragraph>
        <Box>
          <OutboundLink to="https://www.fishhabitat.org/">
            <Image
              src={NFHPLogo}
              sx={{ width: '264px', height: '56px' }}
              alt="National Fish Habitat Partnership logo"
            />
          </OutboundLink>
        </Box>
      </Grid>

      <Heading as="h4" sx={{ mt: '3rem' }}>
        View more about the status of the inventory in each Fish Habitat
        Partnership:
      </Heading>
      {/* <Box as="ul" sx={{ mt: '0.5rem', ml: '1rem' }}>
        {Object.entries(FISH_HABITAT_PARTNERSHIPS)
          .sort(([leftId], [rightId]) => (leftId < rightId ? -1 : 1))
          .map(([id, { name }]) => (
            <Box key={id} as="li">
              <Link to={`/fhp/${id}`}>{name}</Link>
            </Box>
          ))}
      </Box> */}
      <Grid columns={3} gap={4} sx={{ mt: '1rem', bg: 'grey.0', p: '1rem' }}>
        {Object.entries(FISH_HABITAT_PARTNERSHIPS)
          .sort(([leftId], [rightId]) => (leftId < rightId ? -1 : 1))
          .map(([id, { name }]) => (
            <Link key={id} to={`/fhp/${id}`}>
              <Box
                sx={{
                  p: '1rem',
                  bg: '#FFF',
                  border: '1px solid',
                  borderColor: 'grey.1',
                  borderRadius: '0.5rem',
                  height: '100%',
                  '&:hover': {
                    borderColor: 'grey.8',
                    boxShadow: '1px 1px 3px #333',
                  },
                }}
              >
                <Flex
                  sx={{
                    justifyContent: 'flex-end',
                    flexDirection: 'column',
                    height: '3rem',
                  }}
                >
                  <Heading
                    as="h4"
                    sx={{
                      flex: '0 0 auto',
                      fontWeight: 'normal',
                      mr: '0.5rem',
                    }}
                  >
                    {name}
                  </Heading>
                </Flex>

                <Box sx={{ border: '1px solid', borderColor: 'grey.4' }}>
                  <Image
                    src={dynamicallyLoadImage(`maps/fhp/${id}.png`)}
                    alt={`${name} region map`}
                  />
                </Box>
              </Box>
            </Link>
          ))}
      </Grid>
    </Container>
  </Layout>
)

FHPListPage.propTypes = {
  data: PropTypes.shape({
    headerImage: PropTypes.object.isRequired,
  }).isRequired,
}

export const pageQuery = graphql`
  query FHPListPageQuery {
    headerImage: file(relativePath: { eq: "34597621345_26d60382fd_o.jpg" }) {
      childImageSharp {
        gatsbyImageData(
          layout: FULL_WIDTH
          formats: [AUTO, WEBP]
          placeholder: BLURRED
        )
      }
    }
  }
`

export default FHPListPage

export const Head = () => <SEO title="Fish Habitat Partnerships" />
