// ui/src/lib/components/workflow/Filters.svelte
<script lang="ts">
	import ResetIcon from '@lucide/svelte/icons/circle-x'
	import WarningIcon from '@lucide/svelte/icons/triangle-alert'
	import { op } from 'arquero'
	import type { RowObject } from 'arquero/dist/types/table/types'

	import { barrierTypeLabels } from '$lib/config/constants'
	import { Alert } from '$lib/components/alert'
	import { Button } from '$lib/components/ui/button'
	import { FilterGroup } from '$lib/components/filter'
	import { Header, Footer } from '$lib/components/sidebar'
	import { ExpandableParagraph } from '$lib/components/text'
	import { reduceToObject } from '$lib/util/data'
	import { formatNumber, pluralize } from '$lib/util/format'
	import { cn } from '$lib/utils'

	import BackButton from './BackButton.svelte'
	import StartOverButton from './StartOverButton.svelte'
	import NextButton from './NextButton.svelte'
	import type { BarrierTypePlural } from '$lib/config/types'

	const {
		networkType,
		title = null,
		crossfilter,
		maxAllowed = Infinity,
		nextStepLabel,
		onBack,
		onStartOver,
		onSubmit
	} = $props()

	const barrierTypeLabel = $derived(barrierTypeLabels[networkType as BarrierTypePlural])

	const countMessage = $derived.by(() => {
		switch (networkType) {
			case 'dams': {
				return `${formatNumber(crossfilter.filteredCount)} ${pluralize('dam', crossfilter.filteredCount)}`
			}
			case 'small_barriers': {
				return `${formatNumber(crossfilter.filteredCount)} road-related ${pluralize('barrier', crossfilter.filteredCount)}`
			}
			case 'combined_barriers':
			case 'largefish_barriers':
			case 'smallfish_barriers': {
				const { dams = 0, small_barriers: smallBarriers = 0 } = crossfilter.data
					.groupby('barriertype')
					.rollup({ _count: (d: RowObject) => op.sum(d._count) })
					.derive({ row: op.row_object() })
					.array('row')
					.reduce(...reduceToObject('barriertype', (d: RowObject) => d._count))

				return `${formatNumber(dams || 0)} ${pluralize(
					'dam',
					dams
				)} and ${formatNumber(smallBarriers)} road-related ${pluralize('barrier', smallBarriers)}`
			}
			case 'road_crossings': {
				return `${formatNumber(crossfilter.filteredCount)} road/stream ${pluralize('crossing', crossfilter.filteredCount)}`
			}
		}
	})

	const handleBack = () => {
		crossfilter.resetFilters()
		onBack()
	}

	const handleReset = () => {
		crossfilter.resetFilters()
	}
</script>

<div class="flex flex-col h-full">
	<Header class="pt-2 pb-1 px-4">
		<BackButton label="modify area of interest" onClick={handleBack} />

		<div class="flex justify-between items-baseline">
			<h2 class="flex-auto text-2xl leading-none">
				{title || `Filter ${barrierTypeLabel}`}
			</h2>

			<Button
				variant="link"
				class={cn(
					'p-0! flex-none items-center justify-end text-accent no-underline hover:no-underline leading-none',
					{ invisible: !crossfilter.hasFilters }
				)}
				onclick={handleReset}
			>
				<ResetIcon class="size-4" />
				reset filters
			</Button>
		</div>
	</Header>

	<div class="flex-auto px-4 pt-2 pb-4 overflow-y-auto overflow-x-hidden">
		<div class="text-muted-foreground text-xs">
			<ExpandableParagraph
				snippet={`[OPTIONAL] Use the filters below to select the ${barrierTypeLabel} that meet
        your needs. Click on a bar to select ${barrierTypeLabel} with that value.`}
			>
				[OPTIONAL] Use the filters below to select the {barrierTypeLabel}
				that meet your needs. Click on a bar to select {barrierTypeLabel}
				with that value. Click on the bar again to unselect. You can combine multiple values across multiple
				filters to select the
				{barrierTypeLabel} that match ANY of those values within a filter and also have the values selected
				across ALL filters.
			</ExpandableParagraph>
		</div>

		<div class="-mx-4 mt-2">
			{#each crossfilter.filterConfig.filter(({ id }: { id: string }) => !crossfilter.emptyGroups.has(id)) as group (group.id)}
				<FilterGroup {...group} {crossfilter} />
			{/each}
		</div>
	</div>

	<Footer class="pt-4">
		<div class="text-sm text-right mr-1 -mt-2 mb-3">
			selected: {countMessage}
		</div>

		{#if crossfilter.filteredCount > maxAllowed}
			<div class="mb-4">
				<Alert title="Too many barriers!">
					You have selected too many barriers for analysis. The limit is {formatNumber(maxAllowed)}.
					Please choose a smaller area of interest or filter your barriers of interest further.
				</Alert>
			</div>
		{:else if crossfilter.filteredCount === 0}
			<div class="mt-1 mb-3 text-xs flex gap-2">
				<WarningIcon class="size-4 flex-none" />
				No barriers selected. Please choose a different area of interest or adjust your filters to select
				barriers for analysis.
			</div>
		{/if}

		<div class="flex justify-between items-center gap-4">
			<StartOverButton {onStartOver} />

			<NextButton
				disabled={crossfilter.filteredCount === 0}
				label={nextStepLabel}
				onClick={onSubmit}
			/>
		</div>
	</Footer>
</div>

// ui/src/components/Priority/Filters.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { TimesCircle } from '@emotion-icons/fa-solid'
import { Box, Flex, Heading, Text } from 'theme-ui'

import { useBarrierType } from 'components/Data'
import { FilterGroup } from 'components/Filters'
import { useCrossfilter } from 'components/Crossfilter'
import { ExpandableParagraph } from 'components/Text'
import { barrierTypeLabels } from 'config'
import { formatNumber, pluralize } from 'util/format'

import BackLink from './BackLink'
import SubmitButton from './SubmitButton'
import StartOverButton from './StartOverButton'

const Filters = ({ onBack, onSubmit, onStartOver }) => {
  const barrierType = useBarrierType()
  const barrierTypeLabel = barrierTypeLabels[barrierType]
  const {
    state: { filteredData: data, filteredCount, hasFilters, emptyGroups },
    filterConfig,
    resetFilters,
  } = useCrossfilter()

  const handleBack = () => {
    resetFilters()
    onBack()
  }

  const handleReset = () => {
    resetFilters()
  }

  let countMessage = null
  switch (barrierType) {
    case 'dams': {
      countMessage = `${formatNumber(filteredCount)} ${pluralize(
        'dam',
        filteredCount
      )}`
      break
    }
    case 'small_barriers': {
      countMessage = `${formatNumber(filteredCount)} road-related ${pluralize(
        'barrier',
        filteredCount
      )}`
      break
    }
    case 'combined_barriers': {
      let dams = 0
      let smallBarriers = 0
      data.forEach(({ barriertype: recordBarrierType }) => {
        if (recordBarrierType === 'dams') {
          dams += 1
        } else {
          smallBarriers += 1
        }
      })

      countMessage = `${formatNumber(dams)} ${pluralize(
        'dam',
        dams
      )} and ${formatNumber(smallBarriers)} road-related ${pluralize(
        'barrier',
        smallBarriers
      )}`
      break
    }
    default: {
      break
    }
  }

  return (
    <Flex
      sx={{
        flexDirection: 'column',
        height: '100%',
      }}
    >
      <Box
        sx={{
          pt: '1rem',
          pb: '0.25rem',
          pr: '0.5rem',
          pl: '1rem',
          bg: '#f6f6f2',
          borderBottom: '1px solid #DDD',
          flex: '0 0 auto',
        }}
      >
        <BackLink label="modify area of interest" onClick={handleBack} />

        <Flex sx={{ justifyContent: 'space-between', alignItems: 'flex-end' }}>
          <Heading as="h3" sx={{ fontSize: '1.5rem', flex: '0 0 auto' }}>
            Filter {barrierTypeLabel}
          </Heading>
          {hasFilters && (
            <Flex
              onClick={handleReset}
              sx={{
                flex: '1 1 auto',
                justifyContent: 'flex-end',
                alignItems: 'center',
                color: 'highlight',
                cursor: 'pointer',
              }}
            >
              <TimesCircle size="1em" />
              <Text sx={{ ml: '0.5rem' }}>reset filters</Text>
            </Flex>
          )}
        </Flex>
      </Box>

      <Box
        sx={{
          px: '1rem',
          pt: '0.5rem',
          overflowY: 'auto',
          overflowX: 'hidden',
          flex: '1 1 auto',
        }}
      >
        <Box sx={{ color: 'grey.7', fontSize: 1, mb: '0.5rem' }}>
          <ExpandableParagraph
            variant="help"
            snippet={`[OPTIONAL] Use the filters below to select the ${barrierTypeLabel} that meet
        your needs. Click on a bar to select ${barrierTypeLabel} with that value.`}
          >
            <Text variant="help" sx={{ display: 'inline' }}>
              [OPTIONAL] Use the filters below to select the {barrierType} that
              meet your needs. Click on a bar to select {barrierType} with that
              value. Click on the bar again to unselect. You can combine
              multiple values across multiple filters to select the{' '}
              {barrierType} that match ANY of those values within a filter and
              also have the values selected across ALL filters.
            </Text>
          </ExpandableParagraph>
        </Box>

        <Box>
          {filterConfig
            .filter(({ id }) => !emptyGroups.has(id))
            .map((group) => (
              <FilterGroup key={group.id} {...group} />
            ))}
        </Box>
      </Box>

      <Box
        sx={{
          flex: '0 0 auto',
          pt: '0.5rem',
          pb: '1rem',
          px: '1rem',
          bg: '#f6f6f2',
          borderTop: '1px solid #DDD',
        }}
      >
        <Text sx={{ fontSize: 1, textAlign: 'right' }}>
          selected: {countMessage}
        </Text>

        <Flex
          sx={{
            justifyContent: 'space-between',
            alignItems: 'center',
            mt: '1rem',
          }}
        >
          <StartOverButton onStartOver={onStartOver} />

          <SubmitButton
            disabled={filteredCount === 0}
            onClick={onSubmit}
            label="Prioritize selected barriers"
            title={
              filteredCount === 0
                ? `No ${barrierTypeLabel} selected for prioritization`
                : null
            }
          />
        </Flex>
      </Box>
    </Flex>
  )
}

Filters.propTypes = {
  onBack: PropTypes.func.isRequired,
  onSubmit: PropTypes.func.isRequired,
  onStartOver: PropTypes.func.isRequired,
}

export default Filters
