// ui/src/lib/components/sidebar/barrierdetails/ScoreChart.svelte
<script lang="ts">
	// All scores are normalized on a 0-1 basis, with 0 being lowest value
	const { label, score, tier } = $props()
</script>

<div class="not-first-of-type:mt-12">
	<div class="text-sm">{label}</div>
	<div class="flex items-center mt-2 gap-5">
		<div class="flex-none text-muted-foreground text-xs">Low</div>

		<div class="flex-auto relative mt-1">
			<div class="h-0.5 bg-grey-2"></div>
			<div
				class="absolute pt-1 -top-4 w-8 h-8 rounded-xl bg-grey-8 -ml-4 text-center color-white"
				style={`left: ${score}%;`}
			>
				{tier}
			</div>
		</div>

		<div class="flex-none text-muted-foreground text-xs">High</div>
	</div>
</div>

// ui/src/components/barriers/ScoreChart.jsx
import React from "react"
import PropTypes from "prop-types"

// All scores are normalized on a 0-1 basis, with 0 being lowest value
const ScoreChart = ({ label, score, lowIcon, highIcon }) => (
    <div className="chart-score">
        <h6 className="title is-6">{label}</h6>
        <div className="flex-container flex-align-center">
            <div>Low</div>
            <div className="domain">
                <div className="domain-line" />
                <div className="marker" style={{ left: `${100 * score}%` }} />
            </div>
            <div>High</div>
        </div>
    </div>
)

ScoreChart.propTypes = {
    label: PropTypes.string.isRequired,
    lowIcon: PropTypes.node,
    highIcon: PropTypes.node,
    score: PropTypes.number.isRequired
}

ScoreChart.defaultProps = {
    lowIcon: null,
    highIcon: null
}

export default ScoreChart
