// ui/src/components/Filters/FilterGroup.jsx
import React, { useState, useCallback } from 'react'
import PropTypes from 'prop-types'
import { TimesCircle, CaretDown, CaretRight } from '@emotion-icons/fa-solid'
import { Box, Flex, Text } from 'theme-ui'

import { useCrossfilter } from 'components/Crossfilter'
import { reduceToObject } from 'util/data'
import { pluralize } from 'util/format'
import Filter from './Filter'

const FilterGroup = ({ id, title, filters }) => {
  const [isOpen, setIsOpen] = useState(false)

  // all filters initially closed
  const [openFilters, setOpenFilters] = useState(() =>
    filters.reduce(...reduceToObject('field', () => false))
  )

  const {
    resetGroupFilters,
    state: { filters: filterState, emptyDimensions },
  } = useCrossfilter()

  const toggle = () => {
    setIsOpen((prev) => !prev)
  }

  const handleFilterToggle = useCallback(
    (field) => () => {
      setOpenFilters((prevState) => ({
        ...prevState,
        [field]: !prevState[field],
      }))
    },
    []
  )

  const handleReset = () => {
    resetGroupFilters(id)
  }

  const hasFilters =
    filters.filter(
      ({ field }) => filterState[field] && filterState[field].size > 0
    ).length > 0

  const availableFilters = filters.filter(
    ({ field, hideIfEmpty }) => !(hideIfEmpty && emptyDimensions.has(field))
  )

  if (availableFilters.length === 0) {
    return null
  }

  return (
    <Box
      sx={{
        mr: '-1rem',
        ml: '-1rem',
        '&:not(:first-of-type)': {
          pt: '0.5rem',
        },
        borderBottom: '1px solid',
        borderBottomColor: 'grey.2',
      }}
    >
      <Flex
        sx={{
          justifyContent: 'space-between',
          py: '0.5rem',
          pl: '0.15rem',
          pr: '1rem',
        }}
      >
        <Flex
          sx={{
            justifyContent: 'flex-start',
            flex: '1 1 auto',
            cursor: 'pointer',
          }}
          onClick={toggle}
        >
          {isOpen ? <CaretDown size="1.5em" /> : <CaretRight size="1.5em" />}
          <Box sx={{ ml: '0.25rem' }}>
            <Text sx={{ fontWeight: 'bold' }}>{title}</Text>
            <Text sx={{ fontSize: 0, color: 'grey.7' }}>
              {availableFilters.length}{' '}
              {pluralize('filter', availableFilters.length)} available
            </Text>
          </Box>
        </Flex>
        <Box
          onClick={handleReset}
          sx={{
            flex: '0 0 auto',
            cursor: 'pointer',
            ml: '1rem',
            color: 'highlight',
            visibility: hasFilters ? 'visible' : 'hidden',
          }}
          title={`Reset all filters in ${title.toLowerCase()}`}
        >
          <TimesCircle size="1em" />
        </Box>
      </Flex>

      {isOpen ? (
        <Box
          sx={{
            pl: '0.25rem',
            pr: '1rem',
            borderLeft: '0.5rem solid',
            borderLeftColor: 'blue.1',
          }}
        >
          {availableFilters.map((filter) => (
            <Filter
              key={filter.field}
              {...filter}
              isOpen={openFilters[filter.field]}
              onToggle={handleFilterToggle(filter.field)}
            />
          ))}
        </Box>
      ) : null}
    </Box>
  )
}

FilterGroup.propTypes = {
  id: PropTypes.string.isRequired,
  title: PropTypes.string.isRequired,
  filters: PropTypes.arrayOf(PropTypes.shape(Filter.propTypes)).isRequired,
}

export default FilterGroup

// ui/src/lib/components/filter/FilterGroup.svelte
<script lang="ts">
	import ResetIcon from '@lucide/svelte/icons/circle-x'
	import ChevronRightIcon from '@lucide/svelte/icons/chevron-right'
	import ChevronDownIcon from '@lucide/svelte/icons/chevron-down'

	import { Button } from '$lib/components/ui/button'
	import { pluralize } from '$lib/util/format'
	import { cn } from '$lib/utils'

	import type { Dimension } from './types'
	import Filter from './Filter.svelte'

	const { id, title, filters: dimensions, crossfilter } = $props()

	// all filters initially closed
	let isOpen: boolean = $state(true)
	let openFilters: Record<string, boolean> = $state({})

	const hasFilters = $derived(
		dimensions.filter(({ field }: Dimension) =>
			crossfilter.filters[field] ? crossfilter.filters[field].size : 0
		).length > 0
	)

	const availableDimensions = $derived(
		dimensions.filter(
			({ field, hideIfEmpty }: Dimension) =>
				!(hideIfEmpty && crossfilter.emptyDimensions.has(field))
		)
	)

	const handleReset = () => {
		crossfilter.resetGroupFilters(id)
	}
</script>

{#if availableDimensions.length > 0}
	<div class="not-last:border-b not-last:border-b-grey-2">
		<div class="grid grid-cols-[1fr_2rem] gap-2 py-2 w-full">
			<div>
				<Button
					variant="ghost"
					class="block text-left justify-start items-start h-auto rounded-none gap-1 pl-0! pr-2 py-1 w-full overflow-hidden"
					onclick={() => {
						isOpen = !isOpen
					}}
				>
					<div class="flex gap-1">
						{#if isOpen}
							<ChevronDownIcon class="size-6 flex-none" />
						{:else}
							<ChevronRightIcon class="size-6 flex-none" />
						{/if}
						<div class="flex-auto text-wrap">
							<div class="font-bold text-lg -mt-1 leading-snug">{title}</div>
							<div class="text-xs text-muted-foreground">
								{availableDimensions.length}
								{pluralize('filter', availableDimensions.length)} available
							</div>
						</div>
					</div>
				</Button>
			</div>

			<div>
				<Button
					variant="ghost"
					class={cn(
						'flex items-start mt-1 h-auto! rounded-full p-0! flex-none text-accent invisible',
						{
							visible: hasFilters
						}
					)}
					title={`Reset all filters in ${title.toLowerCase()}`}
					onclick={handleReset}
				>
					<ResetIcon class="size-5" />
				</Button>
			</div>
		</div>

		{#if isOpen}
			<div class="border-l-8 border-l-blue-1">
				{#each availableDimensions as dimension (dimension.field)}
					<Filter
						{crossfilter}
						{...dimension}
						bind:isOpen={
							() => !!openFilters[dimension.field],
							(v) => {
								openFilters[dimension.field] = v
							}
						}
					/>
				{/each}
			</div>
		{/if}
	</div>
{/if}
