// ui/src/components/Download/StateDownloadTable.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Box, Grid, Paragraph } from 'theme-ui'

import { useStateSummary } from 'components/Data'
import { REGIONS, STATES } from 'config'
import { groupBy } from 'util/data'
import { formatNumber } from 'util/format'

import Downloader from './Downloader'

const downloadConfig = { scenario: 'NCWC', layer: 'State' }

const StateDownloadTable = ({
  region,
  dams,
  rankedDams,
  reconDams,
  smallBarriers,
  rankedSmallBarriers,
  totalSmallBarriers,
  ...props
}) => {
  const stateData = groupBy(useStateSummary(), 'id')
  const { states } = REGIONS[region]

  const unrankedDams = dams - rankedDams
  const unrankedBarriers = smallBarriers - rankedSmallBarriers

  return (
    <Box {...props}>
      <Box
        sx={{
          mt: '1rem',
          table: {
            width: '100%',
            thead: {
              fontWeight: 'bold',
              fontSize: 1,
              th: {
                bg: 'grey.0',
                borderBottom: '2px solid',
                borderBottomColor: 'grey.3',
                textAlign: 'left',
                py: '1rem',
              },
              'th + th': {
                ml: '0.5rem',
              },
              'th:first-of-type': {
                width: '16em',
              },
              'th:nth-of-type(2),th:nth-of-type(3),th:nth-of-type(4)': {
                width: '12em',
                flex: '0 0 auto',
              },
              'th:nth-of-type(5),th:nth-of-type(6)': {
                width: '8em',
              },
            },
            tbody: {
              td: {
                py: '0.5em',
                borderBottom: '1px solid',
                borderBottomColor: 'grey.1',
              },
              'td:first-of-type': {
                fontWeight: 'bold',
                pl: '0.5em',
              },
              'td:nth-of-type(5),td:nth-of-type(6)': {
                textAlign: 'right',
              },
              'tr:last-of-type td': {
                bg: 'grey.0',
                borderTop: '2px solid',
                borderTopColor: 'grey.3',
              },
            },
            button: {
              fontSize: 1,
              py: '0.25em',
              px: '0.5em',
            },
          },
        }}
      >
        <table cellPadding="0.5rem" cellSpacing="0">
          <thead>
            <tr>
              <th> </th>
              <th>Inventoried dams</th>
              <th>Reconned dams</th>
              <th>Assessed road-related barriers</th>
              <th> </th>
              <th> </th>
            </tr>
          </thead>
          <tbody>
            {states
              .sort((a, b) => (STATES[a] < STATES[b] ? -1 : 1))
              .map((id) => (
                <tr key={id}>
                  <td>{STATES[id]}</td>
                  <td>{formatNumber(stateData[id].dams)}</td>
                  <td>{formatNumber(stateData[id].reconDams)}</td>
                  <td>{formatNumber(stateData[id].totalSmallBarriers)}</td>
                  <td>
                    <Downloader
                      label="dams"
                      asButton
                      barrierType="dams"
                      disabled={stateData[id].dams === 0}
                      config={{
                        ...downloadConfig,
                        summaryUnits: [{ id }],
                      }}
                    />
                  </td>
                  <td>
                    <Downloader
                      label="barriers"
                      asButton
                      barrierType="small_barriers"
                      disabled={stateData[id].totalSmallBarriers === 0}
                      config={{
                        ...downloadConfig,
                        summaryUnits: [{ id }],
                      }}
                    />
                  </td>
                </tr>
              ))}

            <tr>
              <td>Total</td>
              <td>{formatNumber(dams)}</td>
              <td>{formatNumber(reconDams)}</td>
              <td>{formatNumber(totalSmallBarriers)}</td>
              <td>
                <Downloader
                  label="dams"
                  asButton
                  barrierType="dams"
                  disabled={dams === 0}
                  config={{
                    ...downloadConfig,
                    summaryUnits: states.map((id) => ({ id })),
                  }}
                />
              </td>
              <td>
                <Downloader
                  label="barriers"
                  asButton
                  barrierType="small_barriers"
                  disabled={totalSmallBarriers === 0}
                  config={{
                    ...downloadConfig,
                    summaryUnits: states.map((id) => ({ id })),
                  }}
                />
              </td>
            </tr>
          </tbody>
        </table>
      </Box>

      <Grid columns={[0, 2]} gap={4} sx={{ mt: '2rem' }}>
        <Paragraph variant="help">
          <b>{formatNumber(unrankedDams, 0)} inventoried dams</b> and{' '}
          <b>
            {formatNumber(unrankedBarriers, 0)} assessed road-related barriers
          </b>{' '}
          were not analyzed because they could not be correctly located on the
          aquatic network or were otherwise excluded from the analysis. You can
          optionally include these in your download.
        </Paragraph>
        <Paragraph variant="help">
          Note: These statistics are based on <i>inventoried</i> dams and
          road-related barriers. Because the inventory is incomplete in many
          areas, areas with a high number of dams may simply represent areas
          that have a more complete inventory.
        </Paragraph>
      </Grid>
    </Box>
  )
}

StateDownloadTable.propTypes = {
  region: PropTypes.string.isRequired,
  dams: PropTypes.number,
  rankedDams: PropTypes.number,
  reconDams: PropTypes.number,
  smallBarriers: PropTypes.number,
  rankedSmallBarriers: PropTypes.number,
  totalSmallBarriers: PropTypes.number,
}

StateDownloadTable.defaultProps = {
  dams: 0,
  rankedDams: 0,
  reconDams: 0,
  smallBarriers: 0,
  rankedSmallBarriers: 0,
  totalSmallBarriers: 0,
}

export default StateDownloadTable

// ui/src/lib/components/unitSummaryPage/StateDownloadTable.svelte
<script lang="ts">
	import { resolve } from '$app/paths'
	import { Downloader } from '$lib/components/download'
	import { formatNumber } from '$lib/util/format'

	const downloadConfig = { scenario: 'NCWC', layer: 'State' }

	const { total, states, areaName } = $props()

	const stateIds = $derived(states.map(({ id }: { id: string }) => id))
</script>

<h2 class="text-2xl font-bold mt-24">Statistics by state</h2>

<table
	class="w-full mt-2 [&_th]:px-2 [&_th]:py-4 [&_td]:px-2 [&_td]:py-2 [&_tr+tr]:border-t [&_tr+tr]:border-t-grey-1"
>
	<thead class="font-bold bg-grey-1 border-b-2 border-b-grey-3 text-left">
		<tr>
			<th class="w-[16rem]">State</th>
			<th class="w-48">Inventoried dams</th>
			<th class="w-48">Reconned dams</th>
			<th class="w-48">Assessed road-related barriers</th>
			<th aria-label="dams download link column" class="w-32"> </th>
			<th aria-label="road barriers download link column" class="w-32"> </th>
		</tr>
	</thead>
	<tbody>
		{#each states as state (state.id)}
			<tr>
				<td class="font-bold"><a href={resolve(`/states/${state.id}`)}>{state.name}</a></td>
				<td>{formatNumber(state.dams)}</td>
				<td>{formatNumber(state.reconDams)}</td>
				<td>{formatNumber(state.totalSmallBarriers)}</td>
				<td>
					<Downloader
						label="dams"
						barrierType="dams"
						areaName={state.name}
						disabled={state.dams === 0}
						config={{ ...downloadConfig, summaryUnits: { State: [state.id] } }}
						triggerClass="text-sm h-7"
					/>
				</td>
				<td>
					<Downloader
						label="barriers"
						barrierType="small_barriers"
						areaName={state.name}
						disabled={state.totalSmallBarriers === 0}
						config={{ ...downloadConfig, summaryUnits: { State: [state.id] } }}
						triggerClass="text-sm h-7"
					/>
				</td>
			</tr>
		{/each}

		<tr class="border-t-2! border-t-grey-3! bg-grey-1/50">
			<td class="font-bold">Total</td>
			<td class="font-bold">{formatNumber(total.dams)}</td>
			<td class="font-bold">{formatNumber(total.reconDams)}</td>
			<td class="font-bold">{formatNumber(total.totalSmallBarriers)}</td>
			<td>
				<Downloader
					label="dams"
					barrierType="dams"
					{areaName}
					disabled={total.dams === 0}
					config={{ ...downloadConfig, summaryUnits: { State: stateIds } }}
					triggerClass="text-sm h-7"
				/>
			</td>
			<td>
				<Downloader
					label="barriers"
					barrierType="small_barriers"
					{areaName}
					disabled={total.totalSmallBarriers === 0}
					config={{ ...downloadConfig, summaryUnits: { State: stateIds } }}
					triggerClass="text-sm h-7"
				/>
			</td>
		</tr>
	</tbody>
</table>

<div class="grid sm:grid-cols-2 gap-8 mt-8 text-muted-foreground text-sm">
	<div>
		<b>{formatNumber(total.dams - total.rankedDams, 0)} inventoried dams</b> and
		<b>
			{formatNumber(total.smallBarriers - total.rankedSmallBarriers, 0)} assessed road-related barriers
		</b>
		were not analyzed because they could not be correctly located on the aquatic network or were otherwise
		excluded from the analysis. You can optionally include these in your download.
	</div>
	<div>
		Note: These statistics are based on <i>inventoried</i> dams and road-related barriers. Because the
		inventory is incomplete in many areas, areas with a high number of dams may simply represent areas
		that have a more complete inventory.
	</div>
</div>
