// ui/src/lib/components/filter/Filter.svelte
<script lang="ts">
	import ResetIcon from '@lucide/svelte/icons/circle-x'
	import ChevronRightIcon from '@lucide/svelte/icons/chevron-right'
	import ChevronDownIcon from '@lucide/svelte/icons/chevron-down'
	import { SvelteSet } from 'svelte/reactivity'

	import { Button } from '$lib/components/ui/button'
	import { cn } from '$lib/utils'
	import FilterBars from './FilterBars.svelte'

	type Datum = {
		value: number | string
		label: string | number
		quantity: number
		isFiltered: boolean
		isExcluded: boolean
		isMissing: boolean
	}

	let {
		crossfilter,
		field,
		title,
		values,
		labels,
		help,
		url,
		isOpen = $bindable(false),
		hideMissingValues,
		sort
	} = $props()

	const filterValues = $derived(crossfilter.filters[field] || new SvelteSet())
	const hasFilter = $derived(
		crossfilter.filters[field] ? crossfilter.filters[field].size > 0 : false
	)
	const counts: Record<string, number> = $derived(crossfilter.dimensionCounts[field])
	const unfilteredCounts: Record<string, number> = $derived(crossfilter.totalDimensionCounts[field])
	const max = $derived(Math.max(0, ...Object.values(counts)))

	const data: Datum[] = $derived.by(() => {
		// if not isOpen, we can bypass processing the data
		if (!isOpen) {
			return []
		}

		// splice together label, value, and count so that we can filter and sort
		let newData = values.map((value: number | string, i: number) => ({
			value,
			label: labels ? labels[i] : value,
			quantity: counts[value] || 0,
			isFiltered: filterValues.has(value),
			isExcluded: filterValues.size > 0 && !filterValues.has(value),
			// value is not present in the original data
			isMissing: (unfilteredCounts[value] || 0) === 0
		}))

		if (hideMissingValues) {
			newData = newData.filter(({ isMissing }: Datum) => !isMissing)
		}

		if (sort) {
			newData = newData.sort((a: Datum, b: Datum) => {
				if (a.quantity === b.quantity) {
					return a.label < b.label ? -1 : 1
				}
				return a.quantity < b.quantity ? 1 : -1
			})
		}
		return newData
	})

	const handleToggleValue = (value: number | string) => {
		crossfilter.toggleFilterValue(field, value)
	}

	const handleReset = () => {
		crossfilter.resetFilter(field)
	}
</script>

<div class="pb-4 not-first:border-t not-first:border-t-grey-1 not-first:pt-4">
	<div class="grid grid-cols-[1fr_1.5rem] gap-2 pr-2">
		<div>
			<Button
				variant="ghost"
				class="flex text-left justify-start items-start h-auto rounded-none gap-1 pl-0! pr-2 py-1 w-full overflow-hidden"
				onclick={() => {
					isOpen = !isOpen
				}}
			>
				{#if isOpen}
					<ChevronDownIcon class="size-5 flex-none" />
				{:else}
					<ChevronRightIcon class="size-5 flex-none" />
				{/if}

				<div class="flex-auto text-base font-bold text-wrap leading-snug">{title}</div>
			</Button>
		</div>
		<div>
			<Button
				variant="ghost"
				class={cn(
					'flex items-start mt-1 h-auto! rounded-full p-0! flex-none text-accent invisible',
					{
						visible: hasFilter
					}
				)}
				title={`Reset all filters in ${title.toLowerCase()}`}
				onclick={handleReset}
			>
				<ResetIcon class="size-5" />
			</Button>
		</div>
	</div>

	{#if isOpen}
		{#if data.length > 0}
			<div class="pt-2 px-4">
				<FilterBars bars={data} {max} onValueClick={handleToggleValue} />

				{#if help}
					<div class="text-xs text-muted-foreground">
						{help}

						{#if url}
							<a href={url} target="_blank" class="block">Read more.</a>
						{/if}
					</div>
				{/if}
			</div>
		{:else}
			<div class="text-sm text-muted-foreground italic text-center">No data available</div>
		{/if}
	{/if}
</div>

// ui/src/components/FiltersList/Filter.jsx
import React, { useState, useContext } from 'react'
import PropTypes from 'prop-types'
import { Map, Set } from 'immutable'
import { FaRegTimesCircle, FaCaretDown, FaCaretRight } from 'react-icons/fa'

import { HelpText } from 'components/Text'
import { Context as Crossfilter, SET_FILTER } from 'components/Crossfilter'
import { Flex } from 'components/Grid'

import styled, { theme, themeGet } from 'style'
import Bar from './Bar'

const Wrapper = styled.div`
  padding-top: 0.25rem;

  &:not(:first-child) {
    border-top: 1px solid ${themeGet('colors.grey.200')};
  }
`

const Header = styled(Flex).attrs({
  justifyContent: 'space-between',
})``

const Title = styled(Flex).attrs({ alignItems: 'center', flex: 1 })`
  cursor: pointer;
`

const ResetIcon = styled(FaRegTimesCircle).attrs({
  size: '1rem',
})`
  width: 1rem;
  height: 1rem;
  margin-left: 1rem;
  visibility: ${({ visible }) => visible};
  cursor: pointer;
  color: ${themeGet('colors.highlight.500')};
`

const expandoColor = theme.colors.grey[800]
const expandoSize = '1.5rem'

const CaretDown = styled(FaCaretDown).attrs({
  color: expandoColor,
  size: expandoSize,
})`
  width: 1rem;
  height: 1rem;
  margin-right: 0.25rem;
`

const CaretRight = styled(FaCaretRight).attrs({
  color: expandoColor,
  size: expandoSize,
})`
  width: 1rem;
  height: 1rem;
  margin-right: 0.25rem;
`

const Bars = styled.div`
  padding: 0.5rem 0 0 1rem;
`

const EmptyMessage = styled.div`
  color: ${themeGet('colors.grey.600')};
  text-align: center;
  font-style: italic;
  font-size: smaller;
`

const Filter = ({
  field,
  title,
  values,
  labels,
  help,
  isOpen: initIsOpen,
  hideEmpty,
  sort,
}) => {
  const [isOpen, setIsOpen] = useState(initIsOpen)
  const { state, dispatch } = useContext(Crossfilter)

  const filterValues = state.get('filters').get(field, Set())
  const totals = state.get('dimensionTotals').get(field, Map())
  const max = totals.max()

  // splice together label, value, and count so that we can filter and sort
  let data = values.map((value, i) => ({
    value,
    label: labels ? labels[i] : value,
    quantity: totals.get(value, 0),
    isFiltered: filterValues.has(value),
    isExcluded: !filterValues.isEmpty() && !filterValues.has(value),
  }))

  if (hideEmpty) {
    data = data.filter(({ quantity, isFiltered }) => quantity > 0 || isFiltered)
  }

  if (sort) {
    data = data.sort((a, b) => (a.quantity < b.quantity ? 1 : -1))
  }

  const toggle = () => {
    setIsOpen(prev => !prev)
  }

  const handleFilterClick = value => {
    dispatch({
      type: SET_FILTER,
      payload: {
        field,
        // TODO: adapt to other types
        filterValue: filterValues.has(value)
          ? filterValues.delete(value)
          : filterValues.add(value),
      },
    })
  }

  const handleReset = () => {
    dispatch({
      type: SET_FILTER,
      payload: {
        field,
        filterValue: filterValues.clear(),
      },
    })
  }

  return (
    <Wrapper>
      <Header>
        <Title onClick={toggle}>
          {isOpen ? <CaretDown /> : <CaretRight />}
          <div>{title}</div>
        </Title>
        {
          <ResetIcon
            onClick={handleReset}
            visible={filterValues.size > 0 ? 'visible' : 'hidden'}
          />
        }
      </Header>

      {isOpen && (
        <>
          {data.length > 0 ? (
            <Bars>
              {data.map(({ value, ...props }) => (
                <Bar
                  key={value}
                  value={value}
                  {...props}
                  max={max}
                  onClick={() => handleFilterClick(value)}
                />
              ))}

              {help && <HelpText>{help}</HelpText>}
            </Bars>
          ) : (
            <EmptyMessage>No data available</EmptyMessage>
          )}
        </>
      )}
    </Wrapper>
  )
}

Filter.propTypes = {
  field: PropTypes.string.isRequired,
  title: PropTypes.string.isRequired,
  values: PropTypes.array.isRequired,
  labels: PropTypes.array,
  help: PropTypes.string,
  isOpen: PropTypes.bool,
  hideEmpty: PropTypes.bool,
  sort: PropTypes.bool,
}

Filter.defaultProps = {
  labels: null,
  help: null,
  isOpen: false,
  hideEmpty: false,
  sort: false,
}

export default Filter
