// ui/src/content/home/Regions.svelte
<script lang="ts">
	import { resolve } from '$app/paths'

	import { REGIONS } from '$lib/config/constants'

	const mapImages = import.meta.glob('$lib/assets/images/maps/regions/*.png', {
		eager: true,
		import: 'default',
		query: {
			w: '500;250',
			format: 'avif;webp;png',
			as: 'picture'
		}
	})

	const maps: { [key: string]: any } = {}
	for (const path in mapImages) {
		const [region] = path.split('/').slice(-1)[0].split('.')
		maps[region] = mapImages[path]
	}

	type Region = {
		id: string
		order: number
		name: string
		url: string
		inDevelopment?: boolean
	}
	const regions: Region[] = Object.entries(REGIONS)
		.map(([id, rest]) => ({ id, ...rest }))
		.sort(({ order: a }, { order: b }) => (a < b ? -1 : 1))
</script>

<h2 class="text-2xl sm:text-3xl">Explore the inventory by region</h2>

<div class="grid sm:grid-cols-3 gap-6 bg-blue-0 p-4 items-stretch">
	{#each regions as region (region.id)}
		<a
			href={resolve(region.url)}
			class="bg-white p-2 border border-grey-1 rounded-sm h-full flex flex-col justify-end hover:shadow-md hover:border-grey-8 no-underline"
		>
			<div>{region.name}</div>
			{#if region.inDevelopment}
				<div class="text-sm text-muted-foreground">(in development)</div>
			{/if}

			<enhanced:img
				src={maps[region.id]}
				alt={`${region.name} map`}
				class="border border-grey-4 mt-1"
			/>
		</a>
	{/each}
</div>

// ui/src/content/home/Regions.jsx
import React from 'react'
import { Box, Divider, Flex, Grid, Heading } from 'theme-ui'
import { GatsbyImage } from 'gatsby-plugin-image'
import { useStaticQuery, graphql } from 'gatsby'

import { Link } from 'components/Link'
import { REGIONS } from 'config'

const regions = Object.entries(REGIONS)
  .map(([id, data]) => ({ id, ...data }))
  .sort(({ order: a }, { order: b }) => (a < b ? -1 : 1))

const Regions = () => {
  const maps = useStaticQuery(graphql`
    query {
      ak: file(relativePath: { eq: "maps/ak.png" }) {
        childImageSharp {
          gatsbyImageData(
            layout: FULL_WIDTH
            formats: [AUTO, WEBP]
            placeholder: BLURRED
          )
        }
      }
      gl: file(relativePath: { eq: "maps/gl.png" }) {
        childImageSharp {
          gatsbyImageData(
            layout: FULL_WIDTH
            formats: [AUTO, WEBP]
            placeholder: BLURRED
          )
        }
      }
      gpiw: file(relativePath: { eq: "maps/gpiw.png" }) {
        childImageSharp {
          gatsbyImageData(
            layout: FULL_WIDTH
            formats: [AUTO, WEBP]
            placeholder: BLURRED
          )
        }
      }

      ne: file(relativePath: { eq: "maps/ne.png" }) {
        childImageSharp {
          gatsbyImageData(
            layout: FULL_WIDTH
            formats: [AUTO, WEBP]
            placeholder: BLURRED
          )
        }
      }
      pnw: file(relativePath: { eq: "maps/pnw.png" }) {
        childImageSharp {
          gatsbyImageData(
            layout: FULL_WIDTH
            formats: [AUTO, WEBP]
            placeholder: BLURRED
          )
        }
      }
      psw: file(relativePath: { eq: "maps/psw.png" }) {
        childImageSharp {
          gatsbyImageData(
            layout: FULL_WIDTH
            formats: [AUTO, WEBP]
            placeholder: BLURRED
          )
        }
      }
      se: file(relativePath: { eq: "maps/se.png" }) {
        childImageSharp {
          gatsbyImageData(
            layout: FULL_WIDTH
            formats: [AUTO, WEBP]
            placeholder: BLURRED
          )
        }
      }
      sw: file(relativePath: { eq: "maps/sw.png" }) {
        childImageSharp {
          gatsbyImageData(
            layout: FULL_WIDTH
            formats: [AUTO, WEBP]
            placeholder: BLURRED
          )
        }
      }
    }
  `)

  return (
    <Box variant="boxes.section">
      <Divider sx={{ mb: '4rem' }} />
      <Heading as="h2" variant="heading.section">
        Explore the inventory by region:
      </Heading>

      <Grid columns={3} gap={4} sx={{ bg: 'grey.0', p: '1rem' }}>
        {regions.map(({ id, name, url, inDevelopment }) => (
          <Link key={id} to={url}>
            <Box
              sx={{
                p: '1rem',
                bg: '#FFF',
                border: '1px solid',
                borderColor: 'grey.1',
                borderRadius: '0.5rem',
                height: '100%',
                '&:hover': {
                  borderColor: 'grey.8',
                  boxShadow: '1px 1px 3px #333',
                },
              }}
            >
              <Flex
                sx={{
                  justifyContent: 'flex-end',
                  flexDirection: 'column',
                  height: '3rem',
                }}
              >
                <Heading
                  as="h4"
                  sx={{
                    flex: '0 0 auto',
                    fontWeight: 'normal',
                    mr: '0.5rem',
                  }}
                >
                  {name}
                </Heading>
                {inDevelopment ? (
                  <Box
                    sx={{
                      flex: '1 1 auto',
                      fontSize: 1,
                      color: 'grey.8',
                    }}
                  >
                    (in development)
                  </Box>
                ) : null}
              </Flex>

              <Box sx={{ border: '1px solid', borderColor: 'grey.4' }}>
                <GatsbyImage
                  image={maps[id].childImageSharp.gatsbyImageData}
                  alt={`${name} region map`}
                />
              </Box>
            </Box>
          </Link>
        ))}
      </Grid>
    </Box>
  )
}

export default Regions
