// ui/src/content/home/Top.jsx
import React from 'react'
import { Box, Container, Flex, Heading, Grid, Image, Text } from 'theme-ui'

import { siteMetadata } from 'config'
import { useSummaryData } from 'components/Data'
import { OutboundLink } from 'components/Link'
import { formatNumber } from 'util/format'

import NACCLogo from 'images/nacc_logo.svg'

const { naccURL } = siteMetadata

const Top = () => {
  const {
    dams,
    removedDams,
    smallBarriers,
    totalSmallBarriers,
    removedSmallBarriers,
    unsurveyedRoadCrossings,
  } = useSummaryData()

  return (
    <>
      <Container sx={{ mt: '2rem', mb: 0 }}>
        <Flex
          sx={{
            gap: '1rem',
            alignItems: 'flex-end',
            justifyContent: 'center',
          }}
        >
          <OutboundLink to={naccURL}>
            <Image
              src={NACCLogo}
              alt="National Aquatic Connectivity Collaborative logo"
              sx={{ width: '32rem' }}
            />
          </OutboundLink>
        </Flex>
      </Container>

      <Box
        sx={{
          background:
            'radial-gradient(farthest-corner circle at 50% 85% in oklch, oklch(0.4 0.12 240), oklch(0.26 0.08 240))',
        }}
      >
        <Container sx={{ mt: 0, mb: 0, py: '1rem' }}>
          <Heading
            as="h1"
            sx={{
              fontSize: [4, 5, 6],
              lineHeight: 1.1,
              color: '#FFF',
              textShadow: '1px 1px 3px #000',
            }}
          >
            <Box sx={{ fontSize: 4, fontStyle: 'italic' }}>National</Box>
            Aquatic Barrier Inventory
            <br />& Prioritization Tool
          </Heading>
        </Container>
      </Box>

      <Box
        sx={{
          bg: 'blue.0',
          borderBottom: '1px solid',
          borderBottomColor: 'grey.2',
        }}
      >
        <Container sx={{ mt: 0, mb: 0, py: '1rem' }}>
          <Grid columns={[0, 2]} gap={0}>
            <Box>
              <Box sx={{ fontSize: 3, mb: '0.25rem' }}>
                <Text
                  sx={{ display: 'inline', fontWeight: 'bold', fontSize: 4 }}
                >
                  {formatNumber(dams)}
                </Text>{' '}
                inventoried dams
              </Box>
              <Box sx={{ fontSize: 1, color: 'grey.8' }}>
                <b>{formatNumber(removedDams)}</b> removed for conservation
              </Box>
            </Box>
            <Box
              sx={{
                borderLeft: '1px solid',
                borderLeftColor: 'grey.2',
                pl: '1rem',
              }}
            >
              <Box
                sx={{
                  fontSize: 3,
                  mb: '0.25rem',
                }}
              >
                <Text
                  sx={{ display: 'inline', fontWeight: 'bold', fontSize: 4 }}
                >
                  {formatNumber(totalSmallBarriers + unsurveyedRoadCrossings)}
                </Text>{' '}
                road/stream crossings
              </Box>
              <Box sx={{ fontSize: 1, color: 'grey.8' }}>
                <b>{formatNumber(totalSmallBarriers)}</b> assessed for impacts
                to aquatic organisms
                <br />
                <b>{formatNumber(smallBarriers - removedSmallBarriers)}</b>{' '}
                assessed barriers likely to impact aquatic organisms
                <br />
                <b>{formatNumber(removedSmallBarriers)}</b> removed for
                conservation
              </Box>
            </Box>
          </Grid>
        </Container>
      </Box>
    </>
  )
}

export default Top

// ui/src/content/home/Top.svelte
<script lang="ts">
	import { summaryStats } from '$lib/config/summaryStats'
	import { formatNumber } from '$lib/util/format'

	const {
		dams,
		removedDams,
		smallBarriers,
		totalSmallBarriers,
		removedSmallBarriers,
		unsurveyedRoadCrossings
	} = summaryStats
</script>

<div class="bg-blue-0 border-b border-b-grey-2 py-2">
	<div class="container grid sm:grid-cols-2 gap-px bg-grey-1 px-0">
		<div class="bg-blue-0 py-2 sm:py-1 px-4">
			<div>
				<span class="text-lg sm:text-xl md:text-2xl">
					<b>{formatNumber(dams)}</b>
				</span> <span class="text-lg">inventoried dams</span>
			</div>
			<div class="mt-1 text-sm text-muted-foreground">
				<b>{formatNumber(removedDams)}</b> removed for conservation
			</div>
		</div>
		<div class="bg-blue-0 py-2 sm:py-1 px-4">
			<div>
				<span class="text-lg sm:text-xl md:text-2xl">
					<b>{formatNumber(totalSmallBarriers + unsurveyedRoadCrossings)}</b>
				</span> <span class="text-lg">road/stream crossings</span>
			</div>
			<div class="mt-1 text-sm text-muted-foreground">
				<b>{formatNumber(totalSmallBarriers)}</b> assessed for impacts to aquatic organisms
				<br />
				<b>{formatNumber(smallBarriers - removedSmallBarriers)}</b>
				assessed barriers likely to impact aquatic organisms
				<br />
				<b>{formatNumber(removedSmallBarriers)}</b> removed for conservation
			</div>
		</div>
	</div>
</div>
